.\" ==========================================================================
.\"         ____            _                     _____           _
.\"        / ___| _   _ ___| |_ ___ _ __ ___     |_   _|__   ___ | |___
.\"        \___ \| | | / __| __/ _ \ '_ ` _ \ _____| |/ _ \ / _ \| / __|
.\"         ___) | |_| \__ \ ||  __/ | | | | |_____| | (_) | (_) | \__ \
.\"        |____/ \__, |___/\__\___|_| |_| |_|     |_|\___/ \___/|_|___/
.\"               |___/
.\"                             --- System-Tools ---
.\"                  https://www.nntb.no/~dreibh/system-tools/
.\" ==========================================================================
.\"
.\" DER to PEM Conversion
.\" Copyright (C) 2026 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: thomas.dreibholz@gmail.com
.\"
.\" ###### Setup ############################################################
.Dd April 24, 2026
.Dt der2pem 1
.Os der2pem
.\" ###### Name #############################################################
.Sh NAME
.Nm der2pem
.Nd Convert a certificate or CRL from DER to PEM format
.\" ###### Synopsis #########################################################
.\" Manpage syntax help:
.\" https://forums.freebsd.org/threads/howto-create-a-manpage-from-scratch.13200/
.Sh SYNOPSIS
.Nm der2pem
der_file
pem_file
.Nm der2pem
.Op Fl h | Fl Fl help
.Nm der2pem
.Op Fl v | Fl Fl version
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm der2pem
converts a given certificate or CRL file from DER to PEM format.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following options are available:
.Bl -tag -width indent
.It der_file
The certificate or CRL file in DER format to be converted.
.It pem_file
The certificate or CRL file in PEM format to be written.
.It Fl h | Fl Fl help
Prints the program's command-line parameters and exits.
.It Fl v | Fl Fl version
Prints the program version and exits.
.El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It der2pem my-server-certificate.der my-server-certificate.crt
.It der2pem my-crl.der my-crl.crl
.It curl -o google-crl.der http://c.pki.goog/wr2/GSyT1N4PBrg.crl && der2pem google-crl.der google-crl.crl
.It der2pem --help
.It der2pem -h
.It der2pem --version
.It der2pem -v
.El
