#!/usr/bin/env bash
# ==========================================================================
#         ____            _                     _____           _
#        / ___| _   _ ___| |_ ___ _ __ ___     |_   _|__   ___ | |___
#        \___ \| | | / __| __/ _ \ '_ ` _ \ _____| |/ _ \ / _ \| / __|
#         ___) | |_| \__ \ ||  __/ | | | | |_____| | (_) | (_) | \__ \
#        |____/ \__, |___/\__\___|_| |_| |_|     |_|\___/ \___/|_|___/
#               |___/
#                             --- System-Tools ---
#                  https://www.nntb.no/~dreibh/system-tools/
# ==========================================================================
#
# DER to PEM Conversion
# Copyright (C) 2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -eu


# ###### Usage ##############################################################
usage () {
   echo >&2 "Usage: $0 der_file pem_file [-h|--help] [-v|--version]"
   exit 1
}


# ###### Version ############################################################
version () {
   echo "der2pem @BUILD_MAJOR@.@BUILD_MINOR@.@BUILD_PATCH@"
   exit 0
}



# ###### Main program #######################################################

# ====== Handle arguments ===================================================
GETOPT="$(PATH=/usr/local/bin:${PATH} which getopt)"
options="$(${GETOPT} -o hv --long help,version -a -- "$@")"
# shellcheck disable=SC2181
if [[ $? -ne 0 ]]; then
   usage
fi

eval set -- "${options}"
while [ $# -gt 0 ] ; do
   case "$1" in
      -h | --help)
         usage
         # shift
         ;;
      -v | --version)
         version
         # shift
         ;;
      --)
         shift
         break
         ;;
  esac
done
if [ $# -ne 2 ] ; then
   usage
fi

INPUT="$1"
if [ ! -e "${INPUT}" ] ; then
   echo >&2 "ERROR: DER file ${INPUT} does not exist!"
   exit 1
fi
OUTPUT="$2"

TYPE="x509"
# Check whether type is CRL, by using "file":
if [ "$(file -b "${INPUT}")" == "data" ] ; then
   TYPE="crl"
fi

# ====== Convert PEM to DER =================================================
openssl "${TYPE}" \
   -inform der -in "${INPUT}" \
   -outform pem -out "${OUTPUT}"
