#!/usr/bin/env bash
# ==========================================================================
#         ____            _                     _____           _
#        / ___| _   _ ___| |_ ___ _ __ ___     |_   _|__   ___ | |___
#        \___ \| | | / __| __/ _ \ '_ ` _ \ _____| |/ _ \ / _ \| / __|
#         ___) | |_| \__ \ ||  __/ | | | | |_____| | (_) | (_) | \__ \
#        |____/ \__, |___/\__\___|_| |_| |_|     |_|\___/ \___/|_|___/
#               |___/
#                             --- System-Tools ---
#                  https://www.nntb.no/~dreibh/system-tools/
# ==========================================================================
#
# X.509 Certificate Viewer
# Copyright (C) 2025-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -eu


# ###### Main program #######################################################

# ====== Handle arguments ===================================================
if [ $# -ne 2 ] ; then
   echo >&2 "Usage: $0 pem_file der_file"
   exit 1
fi

INPUT="$1"
if [ ! -e "${INPUT}" ] ; then
   echo >&2 "ERROR: ${INPUT} does not exist!"
   exit 1
fi
OUTPUT="$2"

TYPE="x509"
# Check whether type is CRL, by extension or "file":
if [[ "$(basename "${INPUT}")" =~ \.[Cc][Rr][Ll]$ ]] ; then
   TYPE="crl"
# elif [ "$(file -b "${INPUT}")" == "ASCII text" ] ; then
#    TYPE="crl"
fi

# ====== Convert PEM to DER =================================================
openssl "${TYPE}" \
   -inform pem -in "${INPUT}" \
   -outform der -out "${OUTPUT}"
