#!/usr/bin/env bash
# ==========================================================================
#         ____            _                     _____           _
#        / ___| _   _ ___| |_ ___ _ __ ___     |_   _|__   ___ | |___
#        \___ \| | | / __| __/ _ \ '_ ` _ \ _____| |/ _ \ / _ \| / __|
#         ___) | |_| \__ \ ||  __/ | | | | |_____| | (_) | (_) | \__ \
#        |____/ \__, |___/\__\___|_| |_| |_|     |_|\___/ \___/|_|___/
#               |___/
#                             --- System-Tools ---
#                  https://www.nntb.no/~dreibh/system-tools/
# ==========================================================================
#
# X.509 CRL Viewer
# Copyright (C) 2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

# Bash options:
set -euo pipefail

# gettext options:
export TEXTDOMAIN="view-crl"
# export TEXTDOMAINDIR="${PWD}/locale"   # Default: "/usr/share/locale"

# shellcheck disable=SC1091
. gettext.sh


# ###### Usage ##############################################################
usage () {
   local exitCode="$1"
   echo >&2 "$(gettext "Usage:") $0 [-h|--help] [-v|--version] crl [...]"
   exit "${exitCode}"
}


# ###### Version ############################################################
version () {
   echo "view-crl @BUILD_MAJOR@.@BUILD_MINOR@.@BUILD_PATCH@"
   exit 0
}


# ###### Print date in current locale and current time zone #################
print-date ()
{
   local inputDateTime="$1"
   local unixTimestamp
   unixTimestamp="$(time2unixts -T "%b %d %T %Y %Z" "${inputDateTime}")"
   unixts2time -T "%c %Z" "${unixTimestamp}"
}



# ###### Main program #######################################################

# ====== Handle arguments ===================================================
if (( BASH_VERSINFO[0] < 4 )) || (( (BASH_VERSINFO[0] == 4) && (BASH_VERSINFO[1] < 4) )) ; then
   echo "ERROR: Bash 4.4 or higher is required, but Bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} is installed!"
   exit 1
fi
UNAME="$(uname)"
case "${UNAME}" in
   FreeBSD)
      GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt || true)"
      ;;
   NetBSD)
      GETOPT="$(PATH="/usr/pkg/bin:${PATH}" command -v getopt || true)"
      ;;
   OpenBSD)
      GETOPT="$(command -v gnugetopt || true)"
      ;;
   SunOS)
      GETOPT="$(PATH="/usr/gnu/bin:${PATH}" command -v getopt || true)"
      ;;
   Darwin)
      GETOPT="$(env PATH="/opt/homebrew/opt/gnu-getopt/bin:${PATH}" command -v getopt || true)"
      ;;
   *)
      GETOPT="$(command -v getopt || true)"
      ;;
esac
if "${GETOPT}" -T >/dev/null 2>&1 || [[ $? -ne 4 ]]; then
   echo >&2 "ERROR: Enhanced/GNU getopt is required!"
   exit 1
fi
options="$(${GETOPT} -o hv --long help,version -a -- "$@")"
# shellcheck disable=SC2181
if [[ $? -ne 0 ]]; then
   usage 1
fi
eval set -- "${options}"

while [ $# -gt 0 ] ; do
   case "$1" in
      -h | --help)
         usage 0
         ;;
      -v | --version)
         version
         ;;
      --)
         shift
         break
         ;;
      *)
         # This should not happen: wrong getopt parameters, or missing case?
         echo >&2 "INTERNAL ERROR: Unhandled option $1!"
         exit 1
         ;;
  esac
  shift
done
if [ $# -lt 1 ] ; then
   usage 1
fi

# ====== Check availability of tools ========================================
case "${UNAME}" in
   Darwin)
      OPENSSL="$(env PATH="/opt/homebrew/opt/openssl/bin:${PATH}" command -v openssl || true)"
      ;;
   SunOS)
      OPENSSL="$(env PATH="/usr/openssl/3/bin:${PATH}" command -v openssl || true)"
      ;;
   *)
      OPENSSL="$(command -v openssl || true)"
      ;;
esac
if [ "${OPENSSL}" == "" ] ; then
   gettext >&2 "ERROR: OpenSSL is not installed!"
   echo >&2
   exit 1
fi

# ====== Prepare labels and compute indentation =============================
declare -A labels=(
   ["Issuer"]="$(gettext "Issuer:")"
   ["Validity"]="$(gettext "Validity:")"
)

indent=0
for label in "${labels[@]}" ; do
   width="$(print-utf8 --width "${label}")"
   if [ "${width}" -gt "${indent}" ] ; then
      indent="${width}"
   fi
done
indent=-$((indent + 2))

# ====== Check each CRL =====================================================
while [ $# -gt 0 ] ; do

   # ====== Look for CRL ====================================================
   CRL_FILE="$1"
   shift
   if [ "${CRL_FILE}" == "-" ] ; then
      CRL_FILE="/dev/stdin"
   fi
   if [ ! -e "${CRL_FILE}" ] ; then
      eval_gettext >&2 "ERROR: Unable to find CRL file \${CRL_FILE}!"
      echo >&2
      exit 1
   fi

   # ====== Display CRL details =============================================
   echo -e "\e[34m$(eval_gettext "CRL in \${CRL_FILE}:")\e[0m"
   if [ "${CRL_FILE}" == "/dev/stdin" ] || [ "$(file -b "${CRL_FILE}")" == "data" ] ; then
      openssl crl -in "${CRL_FILE}"
   else
      cat "${CRL_FILE}"
   fi | \
   awk '/BEGIN X509 CRL/,/END X509 CRL/' | (
      # ------ Extract each CRL of a combined CRL file ----------------------
      encodedCRL=""
      while read -r line; do
         if [[ "${line}" == *"BEGIN X509 CRL"* ]]; then
            encodedCRL=""
         fi
         encodedCRL+="${line}\n"
         if [[ "${line}" == *"END X509 CRL"* ]]; then
            echo -e "${encodedCRL}" | "${OPENSSL}" crl -noout -text | (
               # ====== Extract CRL details =================================
               while read -r line ; do
                  issuer="?"
                  lastUpdate="?"
                  nextUpdate="?"
                  lastSerialNumber=""
                  declare -A serialNumbers=( )
                  while read -r line ; do
                     if [[ "${line}" =~ ^(Issuer: )(.*)$ ]] ; then
                        # Subject with underlined CN:
                        # shellcheck disable=SC2001
                        issuer="$(sed -e 's|\(CN = [^,]*\)|\x1b[4m\1\x1b[24m|' <<< "${BASH_REMATCH[2]}")"
                     elif [[ "${line}" =~ ^(Last Update: )(.*)$ ]] ; then
                        lastUpdate="${BASH_REMATCH[2]}"
                     elif [[ "${line}" =~ ^(Next Update: )(.*)$ ]] ; then
                        nextUpdate="${BASH_REMATCH[2]}"
                     elif [[ "${line}" =~ ^([ ]*Serial Number: )(.*)$ ]] ; then
                        lastSerialNumber="${BASH_REMATCH[2]}"
                     elif [[ "${line}" =~ ^([ ]*Revocation Date: )(.*)$ ]] ; then
                        serialNumbers["${lastSerialNumber}"]="${BASH_REMATCH[2]}"
                     fi
                  done

                  # ====== Display CRL details ==============================
                  print-utf8 -i "${indent}" "\e[33m${labels["Issuer"]}"
                  echo -e "\e[35m${issuer}\e[0m"

                  print-utf8 -i "${indent}" "\e[33m${labels["Validity"]}"
                  validityFrom="$(print-date "${lastUpdate}")"
                  validityTo="$(print-date "${nextUpdate}")"
                  echo -e "\e[36m${validityFrom}\e[33m — \e[36m${validityTo}\e[0m"

                  entry=0
                  for serialNumber in $(echo "${!serialNumbers[@]}" | tr ' ' '\n' | LC_ALL=C.UTF8 sort) ; do
                     # shellcheck disable=SC2034
                     revocationDate="$(print-date "${serialNumbers[${serialNumber}]}")"
                     entry=$((entry + 1))
                     echo -en " \x1b[31m$(eval_gettext "#\${entry}.") "
                     eval_gettext "Certificate \${serialNumber} revoked on \${revocationDate}"
                     echo -e "\x1b[0m"
                  done
               done
            ) | (
               # Try output via mbuffer. This is faster for console printing, particularly
               # with complex banners and long interface lists. If unavailable, try buffer.
               # Just use cat as fallback, if neither mbuffer nor buffer are available.
               if ! mbuffer -q -s 16k 2>/dev/null ; then
                  if ! buffer -s 16k 2>/dev/null ; then
                     cat
                  fi
               fi
            )
            encodedCRL=""
         fi
      done
   )

   echo -en "\e[0m"

done
