.\" ==========================================================================
.\"         ____            _                     _____           _
.\"        / ___| _   _ ___| |_ ___ _ __ ___     |_   _|__   ___ | |___
.\"        \___ \| | | / __| __/ _ \ '_ ` _ \ _____| |/ _ \ / _ \| / __|
.\"         ___) | |_| \__ \ ||  __/ | | | | |_____| | (_) | (_) | \__ \
.\"        |____/ \__, |___/\__\___|_| |_| |_|     |_|\___/ \___/|_|___/
.\"               |___/
.\"                             --- System-Tools ---
.\"                  https://www.nntb.no/~dreibh/system-tools/
.\" ==========================================================================
.\"
.\" Try-Hard
.\" Copyright (C) 2024-2026 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: thomas.dreibholz@gmail.com
.\"
.\" ###### Setup ############################################################
.Dd May 9, 2026
.Dt try\-hard 1
.Os try\-hard
.\" ###### Name #############################################################
.Sh NAME
.Nm try\-hard
.Nd retries a command multiple times in case of failure
.\" ###### Synopsis #########################################################
.\" Manpage syntax help:
.\" https://forums.freebsd.org/threads/howto-create-a-manpage-from-scratch.13200/
.Sh SYNOPSIS
.Nm try\-hard Ar max\_trials Ar max\_delay
.br
.Op Fl m Ar min\_delay | Fl Fl min\-delay Ar min\_delay
.br
.Op Fl A Ar delay\_increment | Fl Fl additive\-increase Ar delay\_increment
.br
.Op Fl M Ar delay\_factor | Fl Fl multiplicative\-increase Ar delay\_factor
.br
.Op Fl T Ar max\_delay | Fl Fl truncate\-delay Ar truncated\_max\_delay
.br
.Op Fl D | Fl Fl deterministic
.br
.Op Fl q | Fl Fl quiet
.Op Fl w | Fl Fl verbose
.br
\-\-
command ...
.Nm try\-hard
.Op Fl h | Fl Fl help
.Nm try\-hard
.Op Fl v | Fl Fl version
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm try\-hard
tries to run a command up to a given number of trials max\_trials. In case of failure, the program waits for a specific delay before the next trial.
The delay to wait is by default randomly chosen (using random\-sleep) from the interval
.Bq Ar min\_delay , Ar max\_delay .
Alternatively, in deterministic mode, the delay is always max\_delay.
For each new trial, it is possible to increase the interval [min\_delay, max\_delay] by a multiplicative\-increase factor as well as an additive\-increase increment. The upper bound for max\_delay can be limited by truncated\_max\_delay to prevent further increases. The initial min\_delay is always the lower bound.
On failure, the exit code of the last failed trial is returned.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following options are available:
.Bl -tag -width indent
.It Ar max\_trials
The maximum number of trials.
.It Ar max\_delay
The maximum delay.
.It Fl m Ar min\_delay | Fl Fl min\-delay Ar min\_delay
Sets the minimum delay min\_delay (default: 0.0).
.It Fl A Ar delay\_increment | Fl Fl additive\-increase Ar delay\_increment
Sets the additive\-increase delay increment (default: 0.0).
.It Fl M Ar delay\_factor | Fl Fl multiplicative\-increase Ar delay\_factor
Sets the multiplicative\-increase delay factor (default: 1.0).
.It Fl T Ar max\_delay | Fl Fl truncate\-delay Ar truncated\_max\_delay
Sets the truncated\_max\_delay for limiting the increase of max\_delay (default: 31536000.0, i.e. 1 year).
.It Fl D | Fl Fl deterministic
Sets deterministic mode, i.e. turns off randomisation of the delay.
.It Fl q | Fl Fl quiet
Quiet mode: no output is made.
.It Fl w | Fl Fl verbose
Verbose mode: print selected delay and wake\-up.
.It Fl h | Fl Fl help
Prints the program's command\-line parameters and exits.
.It Fl v | Fl Fl version
Prints the program version and exits.
.El
.\" ###### Exit status ######################################################
.Sh EXIT STATUS
The
.Nm
tool exits with 0 on success. On failure, the exit code of the last failed trial is returned.
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It try\-hard 10 60 \-\-verbose \-\- git clone https://dreibh@github.com/dreibh/rserpooldemo.git
.It try\-hard 3 300 \-q \-\- git clone https://git.freebsd.org/ports.git
.It try\-hard 3 65.5 \-\- wget \-O example.tar.gz https://www.example.net/example.tar.gz
.It try\-hard 10 1.0 \-w \-\- false
.It try\-hard 10 2.0 \-\-min\-delay 1.0 \-\-multiplicative\-increase 2.0 \-\-truncate\-delay 3600.0 \-w \-\- false
.It try\-hard 10 1.0 \-m 1 \-M 2 \-T 3600 \-w \-\- false
.It try\-hard 10 1 \-\-min\-delay 0.5 \-\-additive\-increase 5 \-\-truncate\-delay 300 \-w \-\- false
.It try\-hard 10 1 \-m 1 \-A 5 \-T 300 \-w \-\- false
.It try\-hard 10 1.0 \-\-deterministic \-w \-\- false
.It try\-hard 10 1.0 \-D \-w \-\- false
.It try\-hard \-\-version
.It try\-hard \-\-help
.El
.\" ###### See also #########################################################
.Sh SEE ALSO
.Xr random\-sleep 1
.\" ###### Notes ############################################################
.Sh NOTES
This program is part of System\-Tools. The latest version of System\-Tools can be found on the System\-Tools Homepage at
.Lk https://www.nntb.no/\(tidreibh/system\-tools/ "System\-Tools Homepage" .
.\" ###### Authors ##########################################################
.Sh AUTHORS
Thomas Dreibholz,
.Lk https://www.nntb.no/\(tidreibh "Homepage"
