#!/usr/bin/env bash
# ==========================================================================
#         ____            _                     _____           _
#        / ___| _   _ ___| |_ ___ _ __ ___     |_   _|__   ___ | |___
#        \___ \| | | / __| __/ _ \ '_ ` _ \ _____| |/ _ \ / _ \| / __|
#         ___) | |_| \__ \ ||  __/ | | | | |_____| | (_) | (_) | \__ \
#        |____/ \__, |___/\__\___|_| |_| |_|     |_|\___/ \___/|_|___/
#               |___/
#                             --- System-Tools ---
#                  https://www.nntb.no/~dreibh/system-tools/
# ==========================================================================
#
# Fingerprint-SSH-Keys
# Copyright (C) 2013-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail

# gettext options:
export TEXTDOMAIN="Fingerprint-SSH-Keys"
# export TEXTDOMAINDIR="${PWD}/locale"   # Default: "/usr/share/locale"

# shellcheck disable=SC1091
. gettext.sh


# ###### Usage ##############################################################
usage () {
   local exitCode="$1"
   echo >&2 "$(gettext "Usage:") $0 [-d|--include-deprecated] [-r|--include-raw] [-p|--include-raw-python] [-h|--help] [-v|--version]"
   exit "${exitCode}"
}


# ###### Version ############################################################
version () {
   echo "Fingerprint-SSH-Keys @BUILD_MAJOR@.@BUILD_MINOR@.@BUILD_PATCH@"
   exit 0
}


# ###### Main program #######################################################

# ====== Handle arguments ===================================================
if (( BASH_VERSINFO[0] < 4 )) || (( (BASH_VERSINFO[0] == 4) && (BASH_VERSINFO[1] < 4) )) ; then
   echo "ERROR: Bash 4.4 or higher is required, but Bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} is installed!"
   exit 1
fi
UNAME="$(uname)"
case "${UNAME}" in
   FreeBSD)
      GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt)"
      ;;
   NetBSD)
      GETOPT="$(PATH="/usr/pkg/bin:${PATH}" command -v getopt)"
      ;;
   OpenBSD)
      GETOPT="$(command -v gnugetopt)"
      ;;
   Darwin)
      GETOPT="$(env PATH="/opt/homebrew/opt/gnu-getopt/bin:${PATH}" command -v getopt)"
      ;;
   *)
      GETOPT="$(command -v getopt)"
      ;;
esac
if "${GETOPT}" -T >/dev/null 2>&1 || [[ $? -ne 4 ]]; then
   echo >&2 "ERROR: Enhanced/GNU getopt is required!"
   exit 1
fi
options="$(${GETOPT} -o drphv --long include-deprecated,include-raw,include-raw-python,help,version -a -- "$@")"
# shellcheck disable=SC2181
if [[ $? -ne 0 ]]; then
   usage 1
fi
eval set -- "${options}"

FORMATS="raw ssh dns"
INCLUDE_DEPRECATED=0
INCLUDE_RAW=0
while [ $# -gt 0 ] ; do
   case "$1" in
      -d | --include-deprecated)
         INCLUDE_DEPRECATED=1
         ;;
      -r | --include-raw)
         INCLUDE_RAW=1
         ;;
      -p | --include-raw-python)
         INCLUDE_RAW=2
         ;;
      -h | --help)
         usage 0
         ;;
      -v | --version)
         version
         ;;
      --)
         shift
         break
         ;;
      *)
         # This should not happen: wrong getopt parameters, or missing case?
         echo >&2 "INTERNAL ERROR: Unhandled option $1!"
         exit 1
         ;;
  esac
  shift
done
if [ $# -ne 0 ] ; then
   usage 1
fi


# ====== Print SSH key fingerprints =========================================
if [ -d /etc/ssh ] && command -v ssh-keygen >/dev/null ; then
   hostname="$(hostname -f 2>/dev/null || hostname 2>/dev/null || echo "localhost")"

   for format in ${FORMATS} ; do

      # ====== Print fingerprints in SSH format =============================
      if [ "${format}" == "raw" ] ; then
         if [ ${INCLUDE_RAW} -ne 0 ] ; then
            echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(eval_gettext "Fingerprints of \${hostname} in raw format:")\x1b[0m"
            keyNumber=1
            if [ ${INCLUDE_RAW} -eq 2 ] ; then
               echo "'public-keys': {"
            fi
            while IFS= read -r key ; do
               if [ ${INCLUDE_RAW} -eq 1 ] ; then
                  echo -n "#${keyNumber}: "
                  cut -d' ' -f1,2 <"${key}"
               else
                  type="$(cut -d' ' -f1 <"${key}")"
                  key="$(cut -d' ' -f2 <"${key}")"
                  if [ ${keyNumber} -gt 1 ] ; then
                     echo ","
                  fi
                  echo -n "   '${type}': '${key}'"
               fi
               keyNumber=$((keyNumber+1))
            done < <(find /etc/ssh -maxdepth 1 -name "ssh_host_*.pub" -print | sort)
            if [ ${INCLUDE_RAW} -eq 2 ] ; then
               echo -e "\n}"
            fi
            echo
         fi

      # ====== Print fingerprints in SSH format =============================
      elif [ "${format}" == "ssh" ] ; then
         echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(eval_gettext "Fingerprints of \${hostname} in SSH format:")\x1b[0m"
         keyNumber=1
         while IFS= read -r key ; do
            echo -n "#${keyNumber}: "
            ssh-keygen -lf "${key}" | sed -e "s/^\([0-9]*\) \([^ ]*\) \(.*\) (\(.*\))$/\2 (\4 \1)/g"
            keyNumber=$((keyNumber+1))
         done < <(find /etc/ssh -maxdepth 1 -name "ssh_host_*.pub" -print | sort)
         echo

      # ====== Print fingerprints in DNS format =============================
      elif [ "${format}" == "dns" ] ; then
         echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(eval_gettext "Fingerprints of \${hostname} in DNS RR format:")\x1b[0m"
         while IFS= read -r key ; do
            if [ ${INCLUDE_DEPRECATED} -eq 1 ] ; then
               ssh-keygen -r "${hostname}" -f "${key}" | cut -d' ' -f2,3,4,5,6 | grep '^IN SSHFP [1-9] [1-9]' || true
            else
               # Filter out deprecated DSA key type or SSH-1 hash:
               ssh-keygen -r "${hostname}" -f "${key}" | cut -d' ' -f2,3,4,5,6 | grep '^IN SSHFP [13-9] [2-9]' || true
            fi | while read -r in rrType algorithmID hashID fingerprint ; do
               echo -e "${hostname}\t${in}\t${rrType}\t${algorithmID}\t${hashID}\t${fingerprint}"
            done
         done < <(find /etc/ssh -maxdepth 1 -name "ssh_host_*.pub" -print | sort)
         echo
      fi

   done
fi
