#!/usr/bin/env bash
#
# System-Tools
# Copyright (C) 2002-2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com
#

# Bash options:
set -exu

print-utf8 -n -s '<*' '=' '*>'
for indent in -20 +20 ; do
   echo "Indented ${indent}:"
   print-utf8 -i ${indent} "Test: "
   echo "*"
   print-utf8 -i ${indent} "Test äöüß ÆØÅ: "
   echo "*"
   print-utf8 -i ${indent} "托马斯博士: "
   echo "*"
   print-utf8 -i ${indent} "😀💻: "
   echo "*"
done

print-utf8 -n -s '<😀' '=' '😀>'
echo "Centered:"
print-utf8 -n -c "Test"
print-utf8 -n -c "\x1b[38;2;241;71;29mTest\x1b[0m"
print-utf8 -n -c "äöüß"
print-utf8 -n -c "托马斯博士"

print-utf8 -n -s '<💻😀' '=' '😀💻>'

print-utf8 -l '<💻😀' '=' '😀💻>'
print-utf8 -s '<💻😀' '=' '😀💻>'
print-utf8 -w '<💻😀' '=' '😀💻>'
print-utf8 -a '<💻😀' '=' '😀💻>'

echo "Test passed!"
