.\" ==========================================================================
.\"         ____            _                     _____           _
.\"        / ___| _   _ ___| |_ ___ _ __ ___     |_   _|__   ___ | |___
.\"        \___ \| | | / __| __/ _ \ '_ ` _ \ _____| |/ _ \ / _ \| / __|
.\"         ___) | |_| \__ \ ||  __/ | | | | |_____| | (_) | (_) | \__ \
.\"        |____/ \__, |___/\__\___|_| |_| |_|     |_|\___/ \___/|_|___/
.\"               |___/
.\"                             --- System-Tools ---
.\"                  https://www.nntb.no/~dreibh/system-tools/
.\" ==========================================================================
.\"
.\" Time to Unix Timestamp Conversion
.\" Copyright (C) 2026 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: thomas.dreibholz@gmail.com
.\"
.\" ###### Setup ############################################################
.Dd April 22, 2026
.Dt time2unixts 1
.Os time2unixts
.\" ###### Name #############################################################
.Sh NAME
.Nm time2unixts
.Nd converts date/time strings to Unix timestamps
.\" ###### Synopsis #########################################################
.\" Manpage syntax help:
.\" https://forums.freebsd.org/threads/howto-create-a-manpage-from-scratch.13200/
.Sh SYNOPSIS
.Nm time2unixts
.Op time_string ...
.br
.Op Fl F | Fl Fl float
.Op Fl I | Fl Fl integer-decimal
.Op Fl X | Fl Fl integer-hexadecimal
.Op Fl 0 | Fl Fl integer-0x-hexadecimal
.br
.Op Fl H | Fl Fl human-readable
.br
.Op Fl s | Fl Fl seconds
.Op Fl m | Fl Fl milliseconds
.Op Fl u | Fl Fl microseconds
.Op Fl n | Fl Fl nanoseconds
.Nm time2unixts
.Op Fl h | Fl Fl help
.Nm time2unixts
.Op Fl v | Fl Fl version
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm time2unixts
converts date/time strings in the format %Y-%m-%d %H:%M:%S in UTC to Unix timestamps, which is the time (nanoseconds, microseconds, milliseconds, or seconds) since the Unix Epoch, i.e. Jaunary 1, 1970, 00:00:00.000000000 UTC.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following options are available:
.Bl -tag -width indent
.It time_string ...
The date/time strings to be converted, as %Y-%m-%d %H:%M:%S[.SSSSSSSSS]. The seconds part may be fractional; the fraction is optional. If no date/time string is provided, the current system time is used.
.It Fl F | Fl Fl float
Print the Unix timestamp as a floating-point number.
.It Fl I | Fl Fl integer-decimal
Print the Unix timestamp as a decimal integer number. This is the default.
.It Fl X | Fl Fl integer-hexadecimal
Print the Unix timestamp as a hexadecimal integer number.
.It Fl 0 | Fl Fl integer-0x-hexadecimal
Print the Unix timestamp as a hexadecimal integer number, prefixed by 0x.
.It Fl H | Fl Fl human-readable
Provide the output in human-readable form. Default: off.
.It Fl s | Fl Fl seconds
The Unix timestamp is printed in seconds. Default is in nanoseconds.
.It Fl m | Fl Fl milliseconds
The Unix timestamp is printed in milliseconds. Default is in nanoseconds.
.It Fl u | Fl Fl microseconds
The Unix timestamp is printed in microseconds. Default is in nanoseconds.
.It Fl n | Fl Fl nanoseconds
The Unix timestamp is printed in nanoseconds. This is the default.
.It Fl h | Fl Fl help
Prints command-line parameters.
.It Fl v | Fl Fl version
Prints program version.
.El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It time2unixts
.It time2unixts --integer-0x-hexadecimal
.It time2unixts --integer-hexadecimal --seconds
.It time2unixts \(dq2026-03-17 10:52:35\(dq --seconds
.It time2unixts \(dq1969-12-20 10:13:20\(dq
.It time2unixts \(dq1955-12-24 22:22:22.000\(dq --milliseconds
.It time2unixts \(dq2026-03-17 08:31:19\(dq --human-readable --seconds
.It time2unixts \(dq2026-03-17 08:31:19\(dq -s
.It time2unixts \(dq1976-09-29 12:12:03.123\(dq -m
.It time2unixts --version
.It time2unixts --help
.El
