.\" ==========================================================================
.\"         ____            _                     _____           _
.\"        / ___| _   _ ___| |_ ___ _ __ ___     |_   _|__   ___ | |___
.\"        \___ \| | | / __| __/ _ \ '_ ` _ \ _____| |/ _ \ / _ \| / __|
.\"         ___) | |_| \__ \ ||  __/ | | | | |_____| | (_) | (_) | \__ \
.\"        |____/ \__, |___/\__\___|_| |_| |_|     |_|\___/ \___/|_|___/
.\"               |___/
.\"                             --- System-Tools ---
.\"                  https://www.nntb.no/~dreibh/system-tools/
.\" ==========================================================================
.\"
.\" Unix Timestamp to Time Conversion
.\" Copyright (C) 2026 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: thomas.dreibholz@gmail.com
.\"
.\" ###### Setup ############################################################
.Dd March 17, 2026
.Dt unixts2time 1
.Os unixts2time
.\" ###### Name #############################################################
.Sh NAME
.Nm unixts2time
.Nd converts a Unix timestamp to a time string
.\" ###### Synopsis #########################################################
.\" Manpage syntax help:
.\" https://forums.freebsd.org/threads/howto-create-a-manpage-from-scratch.13200/
.Sh SYNOPSIS
.Nm unixts2time
.Op unix_timestamp
.br
.Op Fl -F | Fl Fl float
.Op Fl -I | Fl Fl integer
.br
.Op Fl -H | Fl Fl human-readable
.br
.Op Fl -s | Fl Fl seconds
.Op Fl -m | Fl Fl milliseconds
.Op Fl -u | Fl Fl microseconds
.Op Fl -n | Fl Fl nanoseconds
.Nm unixts2time
.Op Fl h | Fl Fl help
.Nm unixts2time
.Op Fl v | Fl Fl version
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm unixts2time
converts a Unix timestamp to a time string in the format %Y-%m-%d %H:%M:%S.
The Unix timestamp is the time (nanoseconds, microseconds, milliseconds, or
seconds) since the Unix Epoch, i.e. Jaunary 1, 1970, 00:00:00.000000000 UTC.
By default the timestamp is in nanoseconds.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following options are available:
.Bl -tag -width indent
.It unix_timestamp
The Unix timestamp to be converted. If not provided, the current system time is used.
.It Fl -F | Fl Fl float
Parse the Unix timestamp as a floating-point number.
.It Fl -I | Fl Fl integer
Parse the Unix timestamp as an integer number.
A prefex of 0x is interpreted as hexadecimal (base 16),
a prefex of 0 is interpreted as octal (base 8).
Otherwise, the number is interpreted as decimal (base 10).
.It Fl -H | Fl Fl human-readable
Provide the output in human-readable form. Default: off.
.It Fl -s | Fl Fl seconds
The Unix timestamp is given in seconds. Default is in nanoseconds.
.It Fl -m | Fl Fl milliseconds
The Unix timestamp is given in milliseconds. Default is in nanoseconds.
.It Fl -u | Fl Fl microseconds
The Unix timestamp is given in microseconds. Default is in nanoseconds.
.It Fl -n | Fl Fl nanoseconds
The Unix timestamp is given in nanoseconds. This is the default.
.It Fl h | Fl Fl help
Prints command-line parameters.
.It Fl v | Fl Fl version
Prints program version.
.El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It unixts2time
.It unixts2time --human-readable --seconds 1773744755
.It unixts2time --human-readable --seconds -- -1000000
.It unixts2time --human-readable --milliseconds -- -442460258000
.It unixts2time 1773736279 --human-readable --seconds
.It unixts2time 1773736279 -s
.It unixts2time 212847000000 --milliseconds
.It unixts2time 212847008123456789 -H
.It unixts2time 0x179cb2ae8af3dd89
.It unixts2time 0x179cb2ae8af3dd89 -H
.It env LANG=en.UTF8 ./unixts2time 212847123.123 -Fs
.It env LANG=de_DE.UTF8 ./unixts2time 212847123,123456789 -Fs
.It unixts2time --version
.It unixts2time --help
.El
