#!/usr/bin/env bash

set -eu

(
   while read -r line ; do
      if [[ "${line}" =~ ^([a-zA-Z].*)([[:space:]]+)(#.*)([[:space:]]+)([0-9]+)([[:space:]]+)([0-9]+)([[:space:]]+)([0-9]+)$ ]] ; then
         name="${BASH_REMATCH[1]}"
         r="${BASH_REMATCH[5]}"
         g="${BASH_REMATCH[7]}"
         b="${BASH_REMATCH[9]}"
         colorName="$(print-utf8 -i -26 "\"${name,,}\", ")"
         printf "   { %s0x%02x, 0x%02x, 0x%02x },\n" "${colorName}" "${r}" "${g}" "${b}"
      fi
   done <html-rgb.txt
) | sort -u
echo "   { nullptr,                  0x00, 0x00, 0x00 }"
