#!/usr/bin/env bash

set -eu

# Prepare X11 color names from rgb.txt in Debian x11-common
# (https://salsa.debian.org/xorg-team/xorg/-/blob/debian-unstable/debian/local/rgb.txt):
(
   while read -r line ; do
      if [[ "${line}" =~ ^([0-9]+)([[:space:]]+)([0-9]+)([[:space:]]+)([0-9]+)([[:space:]]+)([a-zA-Z].*)$ ]] ; then
         r="${BASH_REMATCH[1]}"
         g="${BASH_REMATCH[3]}"
         b="${BASH_REMATCH[5]}"
         name="${BASH_REMATCH[7]}"
         printf "   { %-26s CTET_RGB, { .RGB = { 0x%02x, 0x%02x, 0x%02x } } }\n" "\"${name}\"," "${r}" "${g}" "${b}"
      fi
   done <x11-rgb.txt
) | sort -u | sed '$!s/$/,/'
