.\" ==========================================================================
.\"         ____            _                     _____           _
.\"        / ___| _   _ ___| |_ ___ _ __ ___     |_   _|__   ___ | |___
.\"        \___ \| | | / __| __/ _ \ '_ ` _ \ _____| |/ _ \ / _ \| / __|
.\"         ___) | |_| \__ \ ||  __/ | | | | |_____| | (_) | (_) | \__ \
.\"        |____/ \__, |___/\__\___|_| |_| |_|     |_|\___/ \___/|_|___/
.\"               |___/
.\"                             --- System-Tools ---
.\"                  https://www.nntb.no/~dreibh/system-tools/
.\" ==========================================================================
.\"
.\" GIMP Scripts
.\" Copyright (C) 2013-2026 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: thomas.dreibholz@gmail.com
.\"
.\" ###### Setup ############################################################
.Dd May 9, 2026
.Dt gs-bumpmap 1
.Os gs-bumpmap
.\" ###### Name #############################################################
.Sh NAME
.Nm gs-bumpmap
.Nd applies the GIMP GEGL "Bump Map" filter on an image
.\" ###### Synopsis #########################################################
.\" Manpage syntax help:
.\" https://forums.freebsd.org/threads/howto-create-a-manpage-from-scratch.13200/
.Sh SYNOPSIS
.Nm gs-bumpmap Ar input_filename Ar output_filename
.br
.Op Fl C Ar on|off | Fl Fl compensate-darkening Ar on|off
.br
.Op Fl I Ar on|off | Fl Fl invert Ar on|off
.br
.Op Fl T Ar on|off | Fl Fl tiled Ar on|off
.br
.Op Fl A Ar bearing | Fl Fl azimuth Ar bearing
.br
.Op Fl E Ar bearing | Fl Fl elevation Ar bearing
.br
.Op Fl D Ar depth | Fl Fl depth Ar depth
.br
.Op Fl X Ar value | Fl Fl offset-x Ar value
.br
.Op Fl Y Ar value | Fl Fl offset-y Ar value
.br
.Op Fl W Ar level | Fl Fl waterlevel Ar level
.br
.Op Fl B Ar factor | Fl Fl ambient Ar factor
.br
.Op Fl H Ar all|red|yellow|green|cyan|blue|magenta | Fl Fl hue-range Ar all|red|yellow|green|cyan|blue|magenta
.br
.Op Fl O Ar degrees | Fl Fl hue-offset Ar degrees
.br
.Op Fl L Ar adjustment | Fl Fl lightness Ar adjustment
.br
.Op Fl S Ar adjustment | Fl Fl saturation Ar adjustment
.br
.Op Fl V Ar overlap | Fl Fl overlap Ar overlap
.br
.Op Fl q | Fl Fl quiet
.Op Fl w | Fl Fl verbose
.Nm gs-bumpmap
.Op Fl h | Fl Fl help
.Nm gs-bumpmap
.Op Fl v | Fl Fl version
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm gs-bumpmap
runs GIMP to load an image, and applies the
GIMP GEGL "Bump Map" filter
(details:
.Lk https://gegl.org/operations/gegl-bump-map.html "GEGL Bump Map" )
as well as
"Hue-Saturation" adjustment
(details:
.Lk https://docs.gimp.org/3.0/en/gimp-tool-hue-saturation.html "GIMP: Hue-Saturation" )
and stores the result into an output file.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following options are available:
.Bl -tag -width indent
.It Ar input_filename
The input image. Any format supported by GIMP can be used. The format will be detected automatically.
.It Ar output_filename
The name for the output image to be written. Any format supported by GIMP can be used. The format will be detected by the provided file name extension (e.g. .jpeg, .png, .webp, .pdf, ...). An existing output file will be overwritten.
.It Fl C Ar on|off | Fl Fl compensate-darkening Ar on|off
Turns compensation for darkening on or off. Default: on.
.It Fl I Ar on|off | Fl Fl invert Ar on|off
Turns inversion on or off. Default: off.
.It Fl T Ar on|off | Fl Fl tiled Ar on|off
Turns tiling on or off. Default: off.
.It Fl A Ar bearing | Fl Fl azimuth Ar bearing
Sets the azimuth parameter for the "Bump Map" filter. Range: 0.0\-360.0. Default: 135.0.
.It Fl E Ar bearing | Fl Fl elevation Ar bearing
Sets the elevation parameter for the "Bump Map" filter. Range: 0.5\-90.0. Default: 45.0.
.It Fl D Ar depth | Fl Fl depth Ar depth
Sets the depth parameter for the "Bump Map" filter. Range: 1\-65. Default: 20.
.It Fl X Ar value | Fl Fl offset-x Ar value
Sets the offset X parameter for the "Bump Map" filter. Range: \-20000\-20000. Default: 0.
.It Fl Y Ar value | Fl Fl offset-y Ar value
Sets the offset Y parameter for the "Bump Map" filter. Range: \-20000\-20000. Default: 0.
.It Fl W Ar level | Fl Fl waterlevel Ar level
Sets the water level (level that full transparency should represent). Range: 0.0\-1.0. Default: 0.0.
.It Fl B Ar factor | Fl Fl ambient Ar factor
Sets the ambient lighting factor. Range: 0.0\-1.0. Default: 0.0.
.It Fl H Ar all|red|yellow|green|cyan|blue|magenta | Fl Fl hue-range Ar all|red|yellow|green|cyan|blue|magenta
Sets the hue range (affected colors): red, yellow, green, cyan, blue, magenta, or all. Default: all.
.It Fl O Ar degrees | Fl Fl hue-offset Ar degrees
Sets the hue offset. Range: \-180.0\-180.0. Default: 0.0.
.It Fl L Ar adjustment | Fl Fl lightness Ar adjustment
Sets the lightness adjustment. Range: \-100.0\-100.0. Default: 0.0.
.It Fl S Ar adjustment | Fl Fl saturation Ar adjustment
Sets the saturation adjustment. Range: \-100.0\-100.0. Default: 0.0.
.It Fl V Ar overlap | Fl Fl overlap Ar overlap
Sets the overlap. Range: 0.0\-100.0. Default: 0.0.
.It Fl q | Fl Fl quiet
Quiet mode: suppress GIMP console output. This is the default.
.It Fl w | Fl Fl verbose
Verbose mode: print GIMP console output and processing details.
.It Fl h | Fl Fl help
Prints the program's command-line parameters and exits.
.It Fl v | Fl Fl version
Prints the program version and exits.
.El
.\" ###### Exit status ######################################################
.Sh EXIT STATUS
The
.Nm
tool exits with 0 on success, and >0 in case of an error.
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It gs-bumpmap Image1.png BumpMap1.png
.It gs-bumpmap Image3.png BumpMap3.png \-\-hue-range all \-\-hue-offset 120.0 \-\-lightness \-15.0
.It gs-bumpmap \-\-help
.It gs-bumpmap \-h
.It gs-bumpmap \-\-version
.It gs-bumpmap \-v
.El
.\" ###### See also #########################################################
.Sh SEE ALSO
.Xr gs-caption 1 ,
.Xr gs-clothify 1 ,
.Xr gs-glossytext 1 ,
.Xr gs-list-fonts 1 ,
.Xr gs-list-gradients 1 ,
.Xr gs-list-patterns 1 ,
.Xr gs-mosaic 1 ,
.Xr gs-oilify 1 ,
.Xr gs-oldphoto 1 ,
.Xr gs-resize-with-cropping 1 ,
.Xr gs-test-gimp 1
.\" ###### Notes ############################################################
.Sh NOTES
This program is part of System-Tools. The latest version of System-Tools can be found on the System-Tools Homepage at
.Lk https://www.nntb.no/\(tidreibh/system-tools/ "System-Tools Homepage" .
.\" ###### Authors ##########################################################
.Sh AUTHORS
Thomas Dreibholz,
.Lk https://www.nntb.no/\(tidreibh "Homepage"
