.\" ==========================================================================
.\"         ____            _                     _____           _
.\"        / ___| _   _ ___| |_ ___ _ __ ___     |_   _|__   ___ | |___
.\"        \___ \| | | / __| __/ _ \ '_ ` _ \ _____| |/ _ \ / _ \| / __|
.\"         ___) | |_| \__ \ ||  __/ | | | | |_____| | (_) | (_) | \__ \
.\"        |____/ \__, |___/\__\___|_| |_| |_|     |_|\___/ \___/|_|___/
.\"               |___/
.\"                             --- System-Tools ---
.\"                  https://www.nntb.no/~dreibh/system-tools/
.\" ==========================================================================
.\"
.\" GIMP Scripts
.\" Copyright (C) 2013-2026 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: thomas.dreibholz@gmail.com
.\"
.\" ###### Setup ############################################################
.Dd April 24, 2026
.Dt gs-oldphoto 1
.Os gs-oldphoto
.\" ###### Name #############################################################
.Sh NAME
.Nm gs-oldphoto
.Nd applies the GIMP Script-Fu "Old Photo" filter on an image
.\" ###### Synopsis #########################################################
.\" Manpage syntax help:
.\" https://forums.freebsd.org/threads/howto-create-a-manpage-from-scratch.13200/
.Sh SYNOPSIS
.Nm gs-oldphoto
input_filename
output_filename
.br
.Op Fl D Ar on|off | Fl Fl defocus Ar on|off
.br
.Op Fl B  Ar border_size | Fl Fl border-size Ar border_size
.br
.Op Fl S Ar on|off | Fl Fl sepia Ar on|off
.br
.Op Fl M Ar on|off | Fl Fl mottle Ar on|off
.br
.Op Fl q | Fl Fl quiet
.Op Fl w | Fl Fl verbose
.Nm gs-oldphoto
.Op Fl h | Fl Fl help
.Nm gs-oldphoto
.Op Fl v | Fl Fl version
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm gs-oldphoto
runs GIMP to load an image, and applies the GIMP Script-Fu "Old Photo" filter
(details: https://docs.gimp.org/3.0/en/script-fu-old-photo.html).
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following options are available:
.Bl -tag -width indent
.It input_filename
The input image. Any format support by GIMP can be used. The format will be detected automatically.
.It output_filename
The name for the output image to be written. Any format support by GIMP can be used. The format will be detected by the provided file name extension (e.g. .jpeg, .png, .webp, .pdf, ...). An existing output file will be overwritten.
.It Fl D Ar on|off | Fl Fl defocus Ar on|off
Turns defocus on or off. Default: on.
.It Fl B Ar border_size | Fl Fl border-size Ar border_size
Sets the border size for the "Old Photo" filter. Default: 10.
.It Fl S Ar on|off | Fl Fl sepia Ar on|off
Turns sepia on or off. Default: on.
.It Fl M Ar on|off | Fl Fl mottle Ar on|off
Turns defocus on or off. Default: off.
.It Fl w | Fl Fl verbose
Verbose mode: print selected delay and wake-up.
.It Fl h | Fl Fl help
Prints the program's command-line parameters and exits.
.It Fl v | Fl Fl version
Prints the program version and exits.
.El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It gs-oldphoto Bergen.jpeg Bergen-OldPhoto.jpeg
.It gs-oldphoto Bergen.jpeg Bergen-OldPhoto-with-Border20.jpeg --border-size 20 --verbose
.It gs-oldphoto Bergen.jpeg Bergen-OldPhoto-with-Border40.jpeg -B 40
.It gs-oldphoto Portobello.jpeg Portobello-OldPhoto.jpeg --verbose --sepia off --mottle on
.It gs-oldphoto --help
.It gs-oldphoto -h
.It gs-oldphoto --version
.It gs-oldphoto -v
.El
