.\" ==========================================================================
.\"         ____            _                     _____           _
.\"        / ___| _   _ ___| |_ ___ _ __ ___     |_   _|__   ___ | |___
.\"        \___ \| | | / __| __/ _ \ '_ ` _ \ _____| |/ _ \ / _ \| / __|
.\"         ___) | |_| \__ \ ||  __/ | | | | |_____| | (_) | (_) | \__ \
.\"        |____/ \__, |___/\__\___|_| |_| |_|     |_|\___/ \___/|_|___/
.\"               |___/
.\"                             --- System-Tools ---
.\"                  https://www.nntb.no/~dreibh/system-tools/
.\" ==========================================================================
.\"
.\" GIMP Scripts
.\" Copyright (C) 2013-2026 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: thomas.dreibholz@gmail.com
.\"
.\" ###### Setup ############################################################
.Dd April 20, 2026
.Dt gs-oilify 1
.Os gs-oilify
.\" ###### Name #############################################################
.Sh NAME
.Nm gs-oilify
.Nd applies the GIMP GEGL "Oilify" filter on an image
.\" ###### Synopsis #########################################################
.\" Manpage syntax help:
.\" https://forums.freebsd.org/threads/howto-create-a-manpage-from-scratch.13200/
.Sh SYNOPSIS
.Nm gs-oilify
input_filename
output_filename
.br
.Op Fl S Ar masksize | Fl Fl mask-size Ar masksize
.br
.Op Fl I on|off | Fl Fl intensity-mode Ar on|off
.br
.Op Fl q | Fl Fl quiet
.Op Fl w | Fl Fl verbose
.Nm gs-oilify
.Op Fl h | Fl Fl help
.Nm gs-oilify
.Op Fl v | Fl Fl version
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm gs-oilify
runs GIMP to load an image, and applies the GIMP GEGL "Oilify" filter
(details: https://gegl.org/operations/gegl-oilify.html).
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following options are available:
.Bl -tag -width indent
.It input_filename
The input image. Any format support by GIMP can be used. The format will be detected automatically.
.It output_filename
The name for the output image to be written. Any format support by GIMP can be used. The format will be detected by the provided file name extension (e.g. .jpeg, .png, .webp, .pdf, ...). An existing output file will be overwritten.
.It Fl S Ar masksize | Fl Fl mask-size Ar masksize
Specifies the mask size. Range: 2-200. Default: 8
.It Fl I on|off | Fl Fl intensity-mode Ar on|off
Turns intensity mode on or off. Default: on.
.It Fl w | Fl Fl verbose
Verbose mode: print selected delay and wake-up.
.It Fl h | Fl Fl help
Prints command-line parameters.
.It Fl v | Fl Fl version
Prints program version.
.El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It gs-oilify Bergen.jpeg Bergen-Hexagons.png --tile-size 24 --tile-height 4 --tile-spacing 4 --tile-type hexagons --tile-surface rough
.It gs-oilify Bergen.jpeg Bergen-Octagons.webp -S 24 -H 4 -X 4 -T octagons -F smooth -T hexagons -N 1.0
.It gs-oilify Portobello.jpeg Portobello-Octagons.jpeg -S 32 -H 8 -X 8 -T octagons -F smooth -N 1.0
.It gs-oilify --help
.It gs-oilify -h
.It gs-oilify --version
.It gs-oilify -v
.El
