.\" ==========================================================================
.\"         ____            _                     _____           _
.\"        / ___| _   _ ___| |_ ___ _ __ ___     |_   _|__   ___ | |___
.\"        \___ \| | | / __| __/ _ \ '_ ` _ \ _____| |/ _ \ / _ \| / __|
.\"         ___) | |_| \__ \ ||  __/ | | | | |_____| | (_) | (_) | \__ \
.\"        |____/ \__, |___/\__\___|_| |_| |_|     |_|\___/ \___/|_|___/
.\"               |___/
.\"                             --- System-Tools ---
.\"                  https://www.nntb.no/~dreibh/system-tools/
.\" ==========================================================================
.\"
.\" GIMP Scripts
.\" Copyright (C) 2013-2026 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: thomas.dreibholz@gmail.com
.\"
.\" ###### Setup ############################################################
.Dd April 20, 2026
.Dt gs-resize-with-cropping 1
.Os gs-resize-with-cropping
.\" ###### Name #############################################################
.Sh NAME
.Nm gs-resize-with-cropping
.Nd resizes an image, including cropping to fit a changed aspect ratio.
.\" ###### Synopsis #########################################################
.\" Manpage syntax help:
.\" https://forums.freebsd.org/threads/howto-create-a-manpage-from-scratch.13200/
.Sh SYNOPSIS
.Nm gs-resize-with-cropping
input_filename
output_filename
.br
.Op Fl A aspect_ratio | Fl Fl aspect Ar aspect_ratio
.br
.Op Fl A Ar H:V|HxV | Fl Fl aspect Ar H:V|HxV
.br
.Op Fl A Ar A0|...|A9|An | Fl Fl aspect Ar A0|...|A9|An
.br
.Op Fl A Ar keep | Fl Fl aspect Ar keep
.br
.Op Fl W Ar new_width | Fl Fl width Ar new_width
.br
.Op Fl H Ar new_height | Fl Fl height Ar new_height
.br
.Op Fl q | Fl Fl quiet
.Op Fl w | Fl Fl verbose
.Nm gs-resize-with-cropping
.Op Fl h | Fl Fl help
.Nm gs-resize-with-cropping
.Op Fl v | Fl Fl version
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm gs-resize-with-cropping
resizes an image, including cropping to fit a changed aspect ratio.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following options are available:
.Bl -tag -width indent
.It input_filename
The input image. Any format support by GraphicsMagick can be used. The format will be detected automatically.
.It output_filename
The name for the output image to be written. Any format support by GraphicsMagick can be used. The format will be detected by the provided file name extension (e.g. .jpeg, .png, .webp, .pdf, ...). An existing output file will be overwritten.
.It Fl A aspect_ratio | Fl Fl aspect Ar aspect_ratio
Specifies the aspect ratio directly as value (e.g. 1.414214).
.It Fl A Ar H:V|HxV | Fl Fl aspect Ar H:V|HxV
Specifies the aspect ratio as H:V or HxV (e.g. 16:9 or 16x9).
.It Fl A Ar A0|...|A9|An | Fl Fl aspect Ar A0|...|A9|An
Specifies the aspect ratio as DIN An format ratio (A1, A2, ..., A9, or An; i.e. sqrt(2):1 ≈ 1.414213562373).
.It Fl A Ar keep | Fl Fl aspect Ar keep
Leaves the aspect ratio unchanged. This is the default.
.It Fl W Ar new_width | Fl Fl width Ar new_width
Specifies the new width. Then, the new height is calculated based on the configured aspect ratio.
.It Fl H Ar new_height | Fl Fl height Ar new_height
Specifies the new height. Then, the new width is calculated based on the configured aspect ratio.
.It Fl q | Fl Fl quiet
Quiet mode: no output is made.
.It Fl w | Fl Fl verbose
Verbose mode: print selected delay and wake-up.
.It Fl h | Fl Fl help
Prints command-line parameters.
.It Fl v | Fl Fl version
Prints program version.
.El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It gs-resize-with-cropping Bergen.jpeg Bergen-1920-4:3.webp 4:3 1920 --verbose
.It gs-resize-with-cropping Bergen.jpeg Bergen-1920-16:9.png 16x9 1920
.It gs-resize-with-cropping Bergen.jpeg Bergen-3860-A3.pdf A3 3840
.It gs-resize-with-cropping Bergen.jpeg Bergen-1024-An.jpeg 1.414214 1024
.It gs-resize-with-cropping Portobello.jpeg Portobello-2048-16:9.jpeg -A 16:9 --width 2048 -v
.It gs-resize-with-cropping --help
.It gs-resize-with-cropping -h
.It gs-resize-with-cropping --version
.It gs-resize-with-cropping -v
.El
