.\" ==========================================================================
.\"         ____            _                     _____           _
.\"        / ___| _   _ ___| |_ ___ _ __ ___     |_   _|__   ___ | |___
.\"        \___ \| | | / __| __/ _ \ '_ ` _ \ _____| |/ _ \ / _ \| / __|
.\"         ___) | |_| \__ \ ||  __/ | | | | |_____| | (_) | (_) | \__ \
.\"        |____/ \__, |___/\__\___|_| |_| |_|     |_|\___/ \___/|_|___/
.\"               |___/
.\"                             --- System-Tools ---
.\"                  https://www.nntb.no/~dreibh/system-tools/
.\" ==========================================================================
.\"
.\" GIMP Scripts
.\" Copyright (C) 2013-2026 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: thomas.dreibholz@gmail.com
.\"
.\" ###### Setup ############################################################
.Dd March 18, 2026
.Dt Make-Clothify 1
.Os Make-Clothify
.\" ###### Name #############################################################
.Sh NAME
.Nm Make-Clothify
.Nd applies the GIMP Script-Fu "Clothify" filter on an image
.\" ###### Synopsis #########################################################
.\" Manpage syntax help:
.\" https://forums.freebsd.org/threads/howto-create-a-manpage-from-scratch.13200/
.Sh SYNOPSIS
.Nm Make-Clothify
input_filename
output_filename
.br
.Op Fl x Ar value | Fl Fl blur-x Ar value
.br
.Op Fl y Ar value | Fl Fl blur-y Ar value
.br
.Op Fl a Ar bearing | Fl Fl azimut Ar bearing
.br
.Op Fl e Ar bearing | Fl Fl elevation Ar bearing
.br
.Op Fl d Ar depth | Fl Fl depth Ar depth
.br
.Op Fl q | Fl Fl quiet
.Op Fl w | Fl Fl verbose
.Nm Make-Clothify
.Op Fl h | Fl Fl help
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm Make-Clothify
runs GIMP to load an image, and applies the GIMP Script-Fu "Clothify" filter
(details: https://docs.gimp.org/3.0/en/script-fu-clothify.html).
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following options are available:
.Bl -tag -width indent
.It input_filename
The input image. Any format support by GIMP can be used. The format will be detected automatically.
.It output_filename
The name for the output image to be written. Any format support by GIMP can be used. The format will be detected by the provided file name extension (e.g. .jpeg, .png, .webp, .pdf, ...). An existing output file will be overwritten.
.It Fl x Ar value | Fl Fl blur-x Ar value
Sets the blur X parameter for the "Clothify" filter. Range: 3-100, Default: 3.
.It Fl y Ar value | Fl Fl blur-y Ar value
Sets the blur Y parameter for the "Clothify" filter. Range: 3-100, Default: 3.
.It Fl a Ar bearing | Fl Fl azimut Ar bearing
Sets the azimut parameter for the "Clothify" filter. Range: 0.0-360.0, Default: 135.0.
.It Fl e Ar bearing | Fl Fl elevation Ar bearing
Sets the elevation parameter for the "Clothify" filter. Range: 0.5-90.0, Default: 45.0.
.It Fl d Ar depth | Fl Fl depth Ar depth
Sets the depth parameter for the "Clothify" filter. Range: 1-65, Default: 5.
.It Fl w | Fl Fl verbose
Verbose mode: print selected delay and wake-up.
.It Fl h | Fl Fl help
Prints command-line parameters.
.El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It Make-Clothify Bergen.jpeg Bergen-Clothify.jpeg
.It Make-Clothify Bergen.jpeg Bergen-Clothify-with-Border8.jpeg --depth 8 --verbose
.It Make-Clothify Bergen.jpeg Bergen-Clothify-with-Depth5.jpeg -d 5
.El
