#!/usr/bin/env bash
# ==========================================================================
#         ____            _                     _____           _
#        / ___| _   _ ___| |_ ___ _ __ ___     |_   _|__   ___ | |___
#        \___ \| | | / __| __/ _ \ '_ ` _ \ _____| |/ _ \ / _ \| / __|
#         ___) | |_| \__ \ ||  __/ | | | | |_____| | (_) | (_) | \__ \
#        |____/ \__, |___/\__\___|_| |_| |_|     |_|\___/ \___/|_|___/
#               |___/
#                             --- System-Tools ---
#                  https://www.nntb.no/~dreibh/system-tools/
# ==========================================================================
#
# GIMP Scripts
# Copyright (C) 2013-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -eu


# ###### Main program #######################################################

# ====== Handle arguments ===================================================
usage () {
   local exitCode="$1"
   echo >&2 "Usage: $0 input_image output_image aspect_ratio|H:V|HxV|An|keep [new_width] [--verbose|-v] [--quiet|-q] [--help|-h]"
   exit "${exitCode}"
}

GETOPT="$(PATH=/usr/local/bin:$PATH which getopt)"
# shellcheck disable=SC2068
options="$(${GETOPT} -o b:vqh --long verbose,quiet,help -a -- "$@")"
eval set -- "${options}"

VERBOSE=0
while [ $# -gt 0 ] ; do
   case "$1" in
      -v | --verbose)
         VERBOSE=1
         shift
         ;;
      -q | --quiet)
         VERBOSE=0
         shift
         ;;
      -h | --help)
         usage 0
         ;;
      --)
         shift
         break
         ;;
      *)
         usage 1
         ;;
  esac
done

if [ $# -lt 3 ] ; then
   usage 1
fi
INPUT_FILENAME="$1"
OUTPUT_FILENAME="$2"
ASPECT="$3"
if [ $# -eq 4 ] ; then
   NEW_WIDTH="$4"
else
   NEW_WIDTH=0
fi


# ====== Prepare output aspect ratio ========================================
outputAspectRatio=0
if [ "${ASPECT}" != "keep" ] ; then
   if [[ "${ASPECT}" =~ ^([0-9]+\.{0,1}[0-9]*)([:x])([0-9]+\.{0,1}[0-9]*)$ ]] ; then
      outputAspectRatio=$(LC_NUMERIC=C awk "BEGIN { print ${BASH_REMATCH[1]}/${BASH_REMATCH[3]} }")
   else
      if [[ "${ASPECT}" =~ ^([0-9]+\.{0,1}[0-9]*)$ ]] ; then
         outputAspectRatio="${BASH_REMATCH[1]}"
      else
         if [[ "${ASPECT}" =~ ^[Aa][0-9n]$ ]] ; then
            outputAspectRatio="1.414213562373"   # DIN A<n> is sqrt(2):1 in landscape format
         else
            echo >&2 "ERROR: Bad aspect specification: ${ASPECT}!"
            exit 1
         fi
      fi
   fi
fi


# ====== Obtain image width and height ======================================
if [ ! -f "${INPUT_FILENAME}" ] ; then
   echo >&2 "ERROR: Input file ${INPUT_FILENAME} does not exist!"
   exit 1
fi
inputImageSize="$(gm identify -format "%wx%h" "$INPUT_FILENAME")"
# shellcheck disable=SC2001
inputWidth="$(echo "${inputImageSize}" | sed -e "s/x[0-9]*$//")"
# shellcheck disable=SC2001
inputHeight="$(echo "${inputImageSize}" | sed -e "s/^[0-9]*x//")"
inputAspect="$(LC_NUMERIC=C awk "BEGIN { printf \"%.16f\\n\", ${inputWidth}/${inputHeight} }")"
if [[ "$inputAspect" =~ ^- ]] ; then
   inputAspect="$(LC_NUMERIC=C awk "BEGIN { printf \"%.16f\\n\", 1/${inputAspect} }")"   # Input image is in portrait format => convert aspect
fi
if [ "${outputAspectRatio}" -eq 0 ] ; then
   outputAspectRatio="${inputAspect}"
fi
if [ ${VERBOSE} -ne 0 ] ; then
   echo "Input: ${inputWidth}*${inputHeight} (${inputAspect})"
fi

if [ "${NEW_WIDTH}" -eq 0 ] ; then
   # shellcheck disable=SC2001
   NEW_WIDTH=$(echo "${inputImageSize}" | sed -e "s/x[0-9]*$//")
fi
newHeight="$(LC_NUMERIC=C awk "BEGIN { print int(${NEW_WIDTH}/${outputAspectRatio}) }")"


# ====== Crop image =========================================================
if [[ "$(LC_NUMERIC=C awk "BEGIN { print ${inputAspect}-${outputAspectRatio} }")" =~ ^- ]] ; then   # inputAspect < outputAspectRatio
   croppedInputWidth=${inputWidth}
   croppedInputHeight="$(LC_NUMERIC=C awk "BEGIN { print int(${croppedInputWidth}/${outputAspectRatio}) }")"
else
   croppedInputHeight=${inputHeight}
   croppedInputWidth="$(LC_NUMERIC=C awk "BEGIN { print int(${inputHeight}*${outputAspectRatio}) }")"
fi
cx="$(LC_NUMERIC=C awk "BEGIN { print int(${inputWidth}-${croppedInputWidth})/2 }")"
cy="$(LC_NUMERIC=C awk "BEGIN { print int(${inputHeight}-${croppedInputHeight})/2 }")"
if [ ${VERBOSE} -ne 0 ] ; then
   echo "Crop: ${croppedInputWidth}*${croppedInputHeight} [cx=${cx} cy=${cy}] (${outputAspectRatio}:1)"
fi


# ====== Run "convert" ======================================================
if [ ${VERBOSE} -ne 0 ] ; then
   if [ "${NEW_WIDTH}" != "" ] ; then
      echo "Resize: ${NEW_WIDTH}*${newHeight} + (${outputAspectRatio}:1)"
   fi
fi
rm -f "${OUTPUT_FILENAME}"
gm convert "$INPUT_FILENAME" \
   -crop "${croppedInputWidth}"x"${croppedInputHeight}"+"${cx}"+"${cy}" \
   -resize "${NEW_WIDTH}"x"${newHeight}" \
   +repage \
   "${OUTPUT_FILENAME}"

if [ ${VERBOSE} -ne 0 ] ; then
   echo -n "Done: "
   gm identify "${OUTPUT_FILENAME}"
fi
