#!/usr/bin/env bash
#
# System-Info
# Copyright (C) 2013-2020 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

set -e


# ====== Print banner =======================================================

# NOTE:
# You can produce ASCII text banners with "banner".
# More advanced, UTF-8-capable tools are e.g. figlet and toilet.

echo -en "\x1b[1;34m"
echo "================================================================="
echo -en "\x1b[1;31m"
echo "  #     #                                                   ###"
echo "  #  #  #  ######  #        ####    ####   #    #  ######   ###"
echo "  #  #  #  #       #       #    #  #    #  ##  ##  #        ###"
echo "  #  #  #  #####   #       #       #    #  # ## #  #####     #"
echo "  #  #  #  #       #       #       #    #  #    #  #"
echo "  #  #  #  #       #       #    #  #    #  #    #  #        ###"
echo "   ## ##   ######  ######   ####    ####   #    #  ######   ###"
echo -en "\x1b[1;34m"
echo ""
echo "       You can change this banner in /etc/system-info.d!"
echo "================================================================="
echo -e "\x1b[0m"


exit 1   # With exit code 1, no further files in /etc/system-info.d are processed!

# Use exit code 0 to process further files!
