#!/usr/bin/env bash
#
# Print system information
# Copyright (C) 2013-2024 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

set -e

# Helper function library -> just return when it is not available.
# Exit code 0 will let System-Info continue with the next script!
# shellcheck disable=SC1091
. "$(dirname "$0")/banner-helper" || exit 0


# ====== Print banner =======================================================

# Using 24-bit color codes. This may not work with all terminals!
reset="\x1b[0m"
color1="\x1b[34m"
color2="\x1b[31m"

# ------ Print top separator ------------------------------------------------
echo -en "${color1}"
separator " *💻" "=" "💻*"
echo ""
center "${color1}-- ${color2}$(gettext "Welcome on the System") ${color1}--"

# ------ Print the hostname FQDN as banner ----------------------------------
make-banner "$(hostname -f)" | while IFS= read -r line ; do
   center "${line}"
done

# ------ Print bottom separator ---------------------------------------------
echo -en "${reset}${color1}"
separator " *💻" "=" "💻*"
echo -e "${reset}"


exit 1   # With exit code 1, no further files in /etc/system-info.d are processed!

# Use exit code 0 to process further files!
