#!/usr/bin/env bash
# ==========================================================================
#         ____            _                     _____           _
#        / ___| _   _ ___| |_ ___ _ __ ___     |_   _|__   ___ | |___
#        \___ \| | | / __| __/ _ \ '_ ` _ \ _____| |/ _ \ / _ \| / __|
#         ___) | |_| \__ \ ||  __/ | | | | |_____| | (_) | (_) | \__ \
#        |____/ \__, |___/\__\___|_| |_| |_|     |_|\___/ \___/|_|___/
#               |___/
#                             --- System-Tools ---
#                  https://www.nntb.no/~dreibh/system-tools/
# ==========================================================================
#
# System-Maintenance
# Copyright (C) 2013-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -euo pipefail

# gettext options:
export TEXTDOMAIN="System-Maintenance"
# export TEXTDOMAINDIR="${PWD}/locale"   # Default: "/usr/share/locale"

# shellcheck disable=SC1091
. gettext.sh


# ###### Usage ##############################################################
usage () {
   local exitCode="$1"
   echo >&2 "$(gettext "Usage:") $0 [-k|--interactive-kernel-removal] [-h|--help] [-v|--version]"
   exit "${exitCode}"
}


# ###### Version ############################################################
version () {
   echo "System-Maintenance @BUILD_MAJOR@.@BUILD_MINOR@.@BUILD_PATCH@"
   exit 0
}



# ###### Main program #######################################################

# ====== Handle arguments ===================================================
if (( BASH_VERSINFO[0] < 4 )) || (( (BASH_VERSINFO[0] == 4) && (BASH_VERSINFO[1] < 4) )) ; then
   echo "ERROR: Bash 4.4 or higher is required, but Bash ${BASH_VERSINFO[0]}.${BASH_VERSINFO[1]} is installed!"
   exit 1
fi
UNAME="$(uname)"
case "${UNAME}" in
   FreeBSD)
      GETOPT="$(PATH="/usr/local/bin:${PATH}" command -v getopt || true)"
      ;;
   NetBSD)
      GETOPT="$(PATH="/usr/pkg/bin:${PATH}" command -v getopt || true)"
      ;;
   OpenBSD)
      GETOPT="$(command -v gnugetopt || true)"
      ;;
   Darwin)
      GETOPT="$(env PATH="/opt/homebrew/opt/gnu-getopt/bin:${PATH}" command -v getopt || true)"
      ;;
   *)
      GETOPT="$(command -v getopt || true)"
      ;;
esac
if "${GETOPT}" -T >/dev/null 2>&1 || [[ $? -ne 4 ]]; then
   echo >&2 "ERROR: Enhanced/GNU getopt is required!"
   exit 1
fi
options="$(${GETOPT} -o khv --long interactive-kernel-removal,help,version -a -- "$@")"
# shellcheck disable=SC2181
if [[ $? -ne 0 ]]; then
   usage 1
fi
eval set -- "${options}"

INTERACTIVE_KERNEL_REMOVAL=0
while [ $# -gt 0 ] ; do
   case "$1" in
      -k | --interactive-kernel-removal)
         INTERACTIVE_KERNEL_REMOVAL=1
         ;;
      -h | --help)
         usage 0
         ;;
      -v | --version)
         version
         ;;
      --)
         shift
         break
         ;;
      *)
         # This should not happen: wrong getopt parameters, or missing case?
         echo >&2 "INTERNAL ERROR: Unhandled option $1!"
         exit 1
         ;;
  esac
  shift
done
if [ $# -ne 0 ] ; then
   usage 1
fi


# ====== Check permissions ==================================================
if [ "${EUID}" -ne 0 ] ; then
   gettext >&2 "ERROR: System-Maintenance requires superuser permissions!"
   echo >&2
   exit 1
fi

# ====== Obtain system details ==============================================
UNAME="$(uname)"
# NAME="${UNAME}"
ID="${UNAME,,}"
# VERSION="$(uname -r)"
# VERSION_ID="${VERSION/_*/}"
if [ -f /etc/os-release ] ; then
   # shellcheck disable=SC1091
   . /etc/os-release
fi


# ====== Stop AutoFS ========================================================
if [ -e /etc/init.d/autofs ] ; then
   echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(gettext "Stopping AutoFS service ...")\x1b[0m"
   service autofs stop >/dev/null 2>&1 || true
fi


# ====== Temporary file handling ============================================
fullPackageList=""
packageVersionsFile=""
installOutputFile=""
trap 'echo ; echo "Aborted." ; rm -f "${installOutputFile}" "${fullPackageList}" "${packageVersionsFile}" ; exit' INT
trap 'rm -f "${installOutputFile}" "${fullPackageList}" "${packageVersionsFile}"' EXIT TERM HUP

installOutputFile="$(mktemp -t SystemMaintenance.install.XXXXXXXXXX)"


# ====== Update package repositories ========================================
echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(gettext "Updating package repositories ...")\x1b[0m"
if [ "${ID}" == "debian" ] || [ "${ID}" == "ubuntu" ] ; then
   DEBIAN_FRONTEND=noninteractive apt-get update -qq

elif [ "${ID}" == "fedora" ] ; then
   dnf makecache

elif [[ "${ID}" =~ ^opensuse- ]] ; then
   zypper --non-interactive refresh

elif [ "${ID}" == "alpine" ] ; then
   apk update

elif [ "${ID}" == "freebsd" ] ; then
   echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(gettext "Updating package repositories ...")\x1b[0m"
   env PAGER=cat freebsd-update fetch || true
   env ASSUME_ALWAYS_YES=yes pkg-static update
   if [ -x /usr/ports/.git ] ; then
      pushd /usr/ports >/dev/null
      git fetch --all
      git pull
      popd >/dev/null
   fi

elif [ "${ID}" == "netbsd" ] ; then
   pkgin update

elif [ "${ID}" == "openbsd" ] ; then
   syspatch -c || true

elif [ "${ID}" == "darwin" ] ; then
   sudo -u "${SUDO_USER}" brew update

else
   echo >&2 "ERROR: Missing repository update case for ${ID}!"
   exit 1
fi


# ====== Try to fix issues ==================================================
if [ "${ID}" == "debian" ] || \
   [ "${ID}" == "ubuntu" ] || \
   [ "${ID}" == "alpine" ] ; then

   echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(gettext "Applying package fixes, if necessary ...")\x1b[0m"

   if [ "${ID}" == "debian" ] || [ "${ID}" == "ubuntu" ] ; then
      # ====== dpkg package fixes ==============================================
      DEBIAN_FRONTEND=noninteractive dpkg --configure -a | tee "${installOutputFile}" || true
      cat "${installOutputFile}"

      # ====== apt-get package fixes ===========================================
      echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(gettext "Installing missing dependencies, if necessary ...")\x1b[0m"
      DEBIAN_FRONTEND=noninteractive nohup apt-get install -f -y -q \
         -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confdef" </dev/null 2>&1 | tee "${installOutputFile}"
      cat "${installOutputFile}"

   elif [ "${ID}" == "alpine" ] ; then
      nohup apk fix </dev/null 2>&1 | tee "${installOutputFile}"
      cat "${installOutputFile}"
   fi
fi


# ====== Install updates ====================================================
echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(gettext "Installing updates ...")\x1b[0m"
if [ "${ID}" == "debian" ] || [ "${ID}" == "ubuntu" ] ; then
   # ------ Download --------------------------------------------------------
   DEBIAN_FRONTEND=noninteractive nohup apt-get dist-upgrade -yd -q \
      -o APT::Get::Always-Include-Phased-Updates=true \
      -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confdef" </dev/null 2>&1 | tee "${installOutputFile}"

   # ------ Update special packages -----------------------------------------
   # NOTE: This block is likely obsolete, and therefore commented out!
   # for package in nornet-server nornet-tunnelbox ; do
   #    if dpkg -l ${package} >/dev/null 2>&1 ; then
   #       if [ "$(find /var/cache/apt/archives/ -name "${package}*.deb")" != "" ] ; then
   #          echo "Updating ${package} package ..."
   #          # Do not restart the service on update, in order to avoid
   #          # unnecessary downtime. Then, a manual restart can be made.
   #          (
   #             echo "#!/bin/sh"
   #             echo "exit 101"
   #          ) | tee /usr/sbin/policy-rc.d >/dev/null
   #          chmod +x /usr/sbin/policy-rc.d
   #          DEBIAN_FRONTEND=noninteractive nohup apt-get install --only-upgrade \
   #             -o APT::Get::Always-Include-Phased-Updates=true \
   #             -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confdef" \
   #            ${package} -y -q </dev/null 2>&1 | tee "${installOutputFile}"
   #          echo "Updated ${package} package."
   #       fi
   #    fi
   # done
   #
   # # Ensure to remove modified policy-rc.d!
   # rm -f /usr/sbin/policy-rc.d

   # ------ Update the rest -------------------------------------------------
   DEBIAN_FRONTEND=noninteractive nohup apt-get dist-upgrade -y -q \
      -o APT::Get::Always-Include-Phased-Updates=true \
      -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confdef" </dev/null 2>&1 | tee "${installOutputFile}"
   cat "${installOutputFile}"

elif [ "${ID}" == "fedora" ] ; then
   dnf upgrade -y 2>&1 | tee "${installOutputFile}"
   cat "${installOutputFile}"

elif [[ "${ID}" =~ ^opensuse- ]] ; then
   if [[ "${PRETTY_NAME}" =~ "Tumbleweed" ]]; then
      nohup zypper --non-interactive dist-upgrade -y </dev/null 2>&1 | tee "${installOutputFile}"
   else
      nohup zypper --non-interactive update -y </dev/null 2>&1 | tee "${installOutputFile}"
   fi
   cat "${installOutputFile}"

elif [ "${ID}" == "alpine" ] ; then
   nohup apk upgrade </dev/null 2>&1 | tee "${installOutputFile}"
   cat "${installOutputFile}"

elif [ "${ID}" == "freebsd" ] ; then
   (
     freebsd-update install || true
     env ASSUME_ALWAYS_YES=yes pkg-static upgrade -y
     if [ -x /usr/sbin/portsnap ] ; then
        /usr/sbin/portsnap -I update
     fi
   ) 2>&1 | tee "${installOutputFile}"
   cat "${installOutputFile}"

elif [ "${ID}" == "netbsd" ] ; then
   nohup pkgin -y upgrade </dev/null 2>&1 | tee "${installOutputFile}"
   cat "${installOutputFile}"

elif [ "${ID}" == "openbsd" ] ; then
   (
      syspatch || true
      pkg_add -u -I
   ) 2>&1 | tee "${installOutputFile}"
   cat "${installOutputFile}"

elif [ "${ID}" == "darwin" ] ; then
   (
      sudo -u "${SUDO_USER}" brew upgrade
   ) 2>&1 | tee "${installOutputFile}"
   cat "${installOutputFile}"

else
   echo >&2 "ERROR: Missing package update case for ${ID}!"
   exit 1
fi


# ====== Auto-remove ========================================================
echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(gettext "Cleaning up ...")\x1b[0m"
if [ "${ID}" == "debian" ] || [ "${ID}" == "ubuntu" ] ; then
   # ------ Remove unnecessary dependencies ---------------
   DEBIAN_FRONTEND=noninteractive nohup apt-get autoremove -y -q \
      -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confdef" </dev/null 2>&1 | tee "${installOutputFile}"
   cat "${installOutputFile}"

   # ------ Purge all previously-removed packages ---------
   dpkg --get-selections | awk '$2=="deinstall" { print $1 }' | DEBIAN_FRONTEND=noninteractive xargs --no-run-if-empty apt-get purge -y \
      -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confdef" 2>&1 | tee "${installOutputFile}"
   cat "${installOutputFile}"

   # ------ Clean up the package cache --------------------
   DEBIAN_FRONTEND=noninteractive apt-get clean

   # ------ Clean up /var/crash ---------------------------
   if [ -d /var/crash/ ] ; then
      find /var/crash/ -name "*.crash" -exec rm -f {} \;
   fi

elif [ "${ID}" == "fedora" ] ; then
   nohup dnf autoremove -y </dev/null 2>&1 | tee "${installOutputFile}"
   cat "${installOutputFile}"
   dnf clean all

elif [[ "${ID}" =~ ^opensuse- ]] ; then
   zypper clean

elif [ "${ID}" == "alpine" ] ; then
   apk cache clean

elif [ "${ID}" == "freebsd" ] ; then
   env ASSUME_ALWAYS_YES=yes pkg-static autoremove -y
   env ASSUME_ALWAYS_YES=yes pkg-static clean all -y

elif [ "${ID}" == "netbsd" ] ; then
   pkgin clean

elif [ "${ID}" == "openbsd" ] ; then
   pkg_delete -a -I

elif [ "${ID}" == "darwin" ] ; then
   sudo -u "${SUDO_USER}" brew cleanup

else
   echo >&2 "ERROR: Missing clean-up case for ${ID}!"
   exit 1
fi


# ====== Remove obsolete kernel packages ====================================
if [ "${ID}" == "debian" ] || [ "${ID}" == "ubuntu" ] ; then
   echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(gettext "Removing obsolete kernels ...")\x1b[0m"

   kernelType=$(uname -r | sed 's/^\([0-9]*\.[0-9]*\.[0-9]*\|[0-9]*\.[0-9]*\.[0-9]*[-+][^-]*\)-\([a-zA-Z0-9\.+]*\)/\2/')
   kernelBootVersion=$(uname -r | sed "s/-${kernelType}$//")
   kernelDiskVersion=$(find /boot -name "vmlinuz-*-${kernelType}" | sort -rV | head -n1 | sed -e "s/^\/boot\/vmlinuz-//" -e "s/-${kernelType}$//")

   echo "$(gettext "Kernel Type:        ") ${kernelType}"
   echo "$(gettext "Kernel Boot Version:") ${kernelBootVersion}"
   echo "$(gettext "Kernel Disk Version:") ${kernelDiskVersion}"

   # The version will be used in regexp: "+" => "\\+"!
   kernelBootVersion="${kernelBootVersion/+/\\+}"
   kernelDiskVersion="${kernelDiskVersion/+/\\+}"

   packageVersionsFile="$(mktemp -t SystemMaintenance.XXXXXXXXXX)"
   apt-show-versions | awk '{ print $1 }' | sed -e "s/:.*$//g" -e "s/\/.*$//g" | sort >"${packageVersionsFile}"

   packagesToRemove="
      nornet-
      linux-image-
      linux-headers-
      linux-modules-
      linux-objects-
"
   packagesToKeep="
      nornet-

      linux-headers-${kernelBootVersion}
      linux-image-${kernelBootVersion}-${kernelType}
      linux-image-extra-${kernelBootVersion}-${kernelType}
      linux-modules-${kernelBootVersion}-${kernelType}
      linux-modules-.*-${kernelBootVersion}-${kernelType}
      linux-objects-.*-${kernelBootVersion}-${kernelType}

      linux-headers-${kernelDiskVersion}
      linux-image-${kernelDiskVersion}-${kernelType}
      linux-image-extra-${kernelDiskVersion}-${kernelType}
      linux-modules-${kernelDiskVersion}-${kernelType}
      linux-modules-.*-${kernelDiskVersion}-${kernelType}
      linux-objects-.*-${kernelDiskVersion}-${kernelType}

      linux-headers-${kernelType}
      linux-image-${kernelType}
      linux-image-extra-${kernelType}
      linux-modules-nvidia-.*-${kernelType}

      linux-headers-virtual
      linux-image-virtual
      linux-image-extra-virtual
"

   # Create a list of packages to be removed. Packets to keep get a "+"
   # suffix, so apt-get ensures to keep them:
   toBeRemoved="$(
      while read -r line ; do
         mayBeRemoved=0
         for packageToRemove in ${packagesToRemove} ; do
            if [[ ${line} =~ ^${packageToRemove}.*$ ]] ; then
               mayBeRemoved=1
               break
            fi
         done
         if [ ${mayBeRemoved} -eq 1 ] ; then
            toBeKept=0
            for packageToKeep in ${packagesToKeep} ; do
               if [[ ${line} =~ ^${packageToKeep}.*$ ]] ; then
                  # echo >&2 "Keep: ${line}"
                  echo -n "${line}+ "   # Ensure that this package is KEPT!
                  toBeKept=1
                  break
               fi
            done
            if [ ${toBeKept} -eq 0 ] ; then
               # echo >&2 "Remove: ${line}"
               echo -n "${line} "
            fi
        fi
      done <"${packageVersionsFile}"
   )"

   rm -f "${packageVersionsFile}"

   if [ "$(echo "${toBeRemoved}" | xargs -n1 | grep -v ".*+$" || true)" != "" ] ; then

      echo -e "$(gettext "To be removed:")\x1b[31m"
      echo "${toBeRemoved}" | xargs -n1 | grep -v ".*+$" || true
      echo -en "\x1b[0m"
      echo -e "$(gettext "To be kept:")\x1b[32m"
      echo "${toBeRemoved}" | xargs -n1 | grep ".*+$" | sed -e "s/+$//g" || true
      echo -en "\x1b[0m"

      if [ $INTERACTIVE_KERNEL_REMOVAL -eq 0 ] ; then
         # shellcheck disable=SC2086
         DEBIAN_FRONTEND=noninteractive nohup apt-get autoremove -y -qq --purge \
            -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confdef" \
            ${toBeRemoved} </dev/null 2>&1 | tee "${installOutputFile}"
         cat "${installOutputFile}"
      else
         # shellcheck disable=SC2086
         apt-get autoremove --purge \
            -o Dpkg::Options::="--force-confold" -o Dpkg::Options::="--force-confdef" \
            ${toBeRemoved}
      fi

   else
      echo "Nothing to do!"
   fi
fi

rm -f "${installOutputFile}"


# ====== Refresh snaps ======================================================
if command -v snap >/dev/null ; then
   echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(gettext "Refreshing snaps ...")\x1b[0m"
   snap refresh || true
fi


# ====== Firmware updates ===================================================
if command -v fwupdmgr >/dev/null ; then
   echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(gettext "Checking for firmware updates ...")\x1b[0m"
   fwupdmgr refresh || true
   fwupdmgr update  || true
fi


# ====== apt-file cache update ==============================================
echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(gettext "Updating caches ...")\x1b[0m"

# ------ locate -------------------------------------------------------------
if [ -x /etc/periodic/weekly/310.locate ] ; then
   /etc/periodic/weekly/310.locate
elif [ -x /usr/libexec/locate.updatedb ] ; then
   /usr/libexec/locate.updatedb
elif command -v updatedb >/dev/null ; then
   updatedb
fi

# ------ geoipupdate --------------------------------------------------------
if command -v geoipupdate >/dev/null ; then
   geoipupdate
elif [ -x /usr/local/bin/geoipupdate.sh ] ; then
   /usr/local/bin/geoipupdate.sh
fi

# ------ apt-show-versions --------------------------------------------------
if [ "${ID}" == "debian" ] || [ "${ID}" == "ubuntu" ] ; then
   if command -v apt-file >/dev/null ; then
      apt-file update >/dev/null
      apt-show-versions -i
   fi
fi


# ====== Start AutoFS =======================================================
if [ -e /etc/init.d/autofs ] ; then
   echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(gettext "Starting AutoFS service ...")\x1b[0m"
   service autofs start >/dev/null 2>&1 || true
fi


# ====== Fix time ===========================================================
echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(gettext "Synchronising system time ...")\x1b[0m"

# Sychronise time from a reliable NTP servers:
# 1. Try Universitetet i Oslo (UiO) NTP servers.
# 2. Try Physikalisch-Technische Bundesanstalt (PTB) NTP servers.
# 3. Try ISC NTP server (clock.isc.org).
# 4. Try Microsoft as last resort, which is likely allowed in a firewall.
NTP_SERVERS=(
   "ntp2.uio.no"
   "ntp1.uio.no"
   "ntp2.ptb.de"
   "ntp1.ptb.de"
   "clock.isc.org"
   "time.windows.com"
)
updatedTime=0

# ------ Try systemd-timesyncd (modern Debian/Ubuntu) -----------------------
if [ ${updatedTime} -eq 0 ] && command -v timedatectl >/dev/null ; then
   if timedatectl set-ntp false && timedatectl set-ntp true >/dev/null 2>&1 ; then
      updatedTime=1
   fi
fi

# ------ Try chronyd (Fedora, RHEL, newer Debian/Ubuntu) --------------------
if [ ${updatedTime} -eq 0 ] && command -v chronyc >/dev/null ; then
   if chronyc makestep >/dev/null 2>&1 ; then
      updatedTime=1
   fi
fi

# ------ Try BusyBox ntpd (Alpine) ------------------------------------------
if [ ${updatedTime} -eq 0 ] && command -v busybox >/dev/null ; then
   for server in "${NTP_SERVERS[@]}" ; do
      if busybox ntpd -q -n -p "${server}" ; then
         updatedTime=1
         break
      fi
   done
fi

# ------ Try ntpdate (FreeBSD) ----------------------------------------------
if [ ${updatedTime} -eq 0 ] && command -v ntpdate >/dev/null ; then
   for ntpServiceName in ntpd ntp ; do
      service ${ntpServiceName} stop >/dev/null 2>&1 || true
   done
   for server in "${NTP_SERVERS[@]}" ; do
      if ntpdate "${server}" ; then
         updatedTime=1
         break
      fi
   done
   for ntpServiceName in ntpd ntp ; do
      service ${ntpServiceName} start >/dev/null 2>&1 || true
   done
fi

# ------ Try OpenNTPD (OpenBSD) ---------------------------------------------
if [ ${updatedTime} -eq 0 ] && command -v rcctl >/dev/null ; then
   rcctl stop ntpd || true
   rcctl set ntpd flags -s
   rcctl start ntpd || true
   updatedTime=1
fi

# ------ Write updated time to hardware clock -------------------------------
if [ ${updatedTime} -eq 1 ] ; then
   # shellcheck disable=SC2034
   now="$(date)"
   eval_gettext "Updated system time to \${now}."
   echo
   if command -v hwclock >/dev/null ; then
      hwclock -w
   elif [ "${ID}" == "freebsd" ] ; then
      date -v +0S
   fi
else
   gettext "No system time update possible."
   echo
fi


# ====== SSD trimming =======================================================
if command -v fstrim >/dev/null ; then
   echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(gettext "Running fstrim ...")\x1b[0m"
   fstrim -a -v 2>/dev/null || ( fstrim -v / && fstrim -v /home ) || true
fi
if command -v zpool >/dev/null ; then
   zpools="$(zpool list -H 2>/dev/null | cut -f1 || true)"
   if [ -n "${zpools}" ] ; then
      echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(gettext "Running zpool trim ...")\x1b[0m"
      for zpool in ${zpools} ; do
         echo "${zpool}"
         zpool trim "${zpool}" || true
      done
   fi
fi


# ====== Done! ==============================================================
echo -e "\x1b[34m$(date +%FT%H:%M:%S): $(gettext "Done!")\x1b[0m"


# ====== Finally, show project package versions =============================
filterScripts=()
for directory in /etc/system-maintenance.d /usr/local/etc/system-maintenance.d ; do
   if [ -d "${directory}" ] ; then
      while IFS= read -r scriptPath ; do
         filterScripts+=( "${scriptPath}" )
      done < <(find "${directory}" -maxdepth 1 -type f -name "[0-9][0-9]*[^~]" -print | sort -r)
   fi
done

if [ ${#filterScripts[@]} -gt 0 ] ; then
   fullPackageList="$(mktemp -t SystemMaintenance.XXXXXXXXXX)"

   if [ "${ID}" == "debian" ] || [ "${ID}" == "ubuntu" ] ; then
      if command -v apt-show-versions >/dev/null ; then
         apt-show-versions | grep -v "not installed$" >"${fullPackageList}" || true
      fi
   elif [ "${ID}" == "fedora" ] || [[ "${ID}" =~ ^opensuse- ]] ; then
      rpm -qa | sort >"${fullPackageList}" || true
   elif [ "${ID}" == "alpine" ] ; then
      apk info -v | sort >"${fullPackageList}" || true
   elif [ "${ID}" == "freebsd" ] ; then
      pkg info --all | sort  >"${fullPackageList}" || true
   elif [ "${ID}" == "netbsd" ] || [ "${ID}" == "openbsd" ] ; then
      pkg_info | awk '{ print $1 }' | sort >"${fullPackageList}" || true
   elif [ "${ID}" == "darwin" ] ; then
      sudo -u "${SUDO_USER}" brew list
   else
      echo >&2 "ERROR: Missing project package versions case for ${ID}!"
      exit 1
   fi

   if [ -e "${fullPackageList}" ] ; then
      for filterScript in "${filterScripts[@]}" ; do
         "${filterScript}" "${fullPackageList}"
      done
      rm -f "${fullPackageList}"
      echo "=============================================================================="
   fi
fi
