#!/usr/bin/env bash
echo -en "\e[2J\e[H"
print-utf8 -n -s "\e[1;31;40;5m█" "▀" "█\e[0m"
echo -e "Software Failure.   Press left mouse button to continue.\nGuru Meditation #00000004.48454C50" | \
print-utf8 -n -C "\e[1;31;40;5m█\e[25m" "\e[5m█\e[0m"
print-utf8 -n -s "\e[1;31;40;5m█" "▄" "█\e[0m"

# To create the example image from 2 screenshots:
# cwebp ~/Bilder/guru1.png guru1.webp
# cwebp ~/Bilder/guru2.png guru2.webp
# webpmux -frame guru1.webp +1000+0+0+0+b -frame guru2.webp +1000+0+0+0+b -o guru.webp
