#!/usr/bin/env bash

# Doubled width and height per character. Needs two lines!

# Set double-height (top half)
echo -e "\033#3 This is a test!"
# Set double-height (bottom half)
echo -e "\033#4 This is a test!"
