#!/usr/bin/env bash

set -eu

# Prepare HTML color names from table provided in "CSS Color Module Level 3"
# specification (https://www.w3.org/TR/css-color-3/):
(
   while read -r line ; do
      if [[ "${line}" =~ ^([a-zA-Z].*)([[:space:]]+)(#.*)([[:space:]]+)([0-9]+)([[:space:]]+)([0-9]+)([[:space:]]+)([0-9]+)$ ]] ; then
         name="${BASH_REMATCH[1]}"
         r="${BASH_REMATCH[5]}"
         g="${BASH_REMATCH[7]}"
         b="${BASH_REMATCH[9]}"
         printf "   { %-26s CTET_RGB, { .RGB = { 0x%02x, 0x%02x, 0x%02x } } }\n" "\"${name}\"," "${r}" "${g}" "${b}"
      fi
   done <html-rgb.txt
) | sort -u | sed '$!s/$/,/'
