#!/usr/bin/env bash
#
# System-Info
# Copyright (C) 2013-2020 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: dreibh@simula.no

set -e

bannerText="$1"

bannerFile=`mktemp`
for sysvbanner in /usr/bin/sysvbanner /usr/local/bin/sysvbanner /usr/bin/banner /usr/bin/echo ] ; do
   if [ -x ${sysvbanner} ] ; then
      ${sysvbanner} "${bannerText}" >${bannerFile}
      break
   fi
done

maxLineLength=`awk 'BEGIN { maxLineLength = 0; } { if(length($0) > maxLineLength) { maxLineLength = length($0); } } END { print maxLineLength; }' ${bannerFile}`

cat ${bannerFile} | (
   IFS=""
   while read line ; do
      if [ "${line}" != "" ] ; then
         printf "center \"%-${maxLineLength}s\"\n" "${line}"
      fi
   done
)
rm -f ${bannerFile}
