.\"         ____            _                     _____           _
.\"        / ___| _   _ ___| |_ ___ _ __ ___     |_   _|__   ___ | |___
.\"        \___ \| | | / __| __/ _ \ '_ ` _ \ _____| |/ _ \ / _ \| / __|
.\"         ___) | |_| \__ \ ||  __/ | | | | |_____| | (_) | (_) | \__ \
.\"        |____/ \__, |___/\__\___|_| |_| |_|     |_|\___/ \___/|_|___/
.\"               |___/
.\"                             --- System-Tools ---
.\"                  https://www.nntb.no/~dreibh/system-tools/
.\" ==========================================================================
.\"
.\" Print-UTF8
.\" Copyright (C) 2024-2025 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: thomas.dreibholz@gmail.com
.\"
.\" ###### Setup ############################################################
.Dd November, 18 2024
.Dt print-utf8 1
.Os print-utf8
.\" ###### Name #############################################################
.Sh NAME
.Nm print-utf8
.Nd Print UTF-8 strings
.\" ###### Synopsis #########################################################
.\" Manpage syntax help:
.\" https://forums.freebsd.org/threads/howto-create-a-manpage-from-scratch.13200/
.Sh SYNOPSIS
.Nm print-utf8
.Op Fl h | Fl Fl help
.Op Fl v | Fl Fl version
.Op Fl n | Fl Fl newline
.br
.Op Fl i Ar indentation Ar string | Fl Fl indent Ar indentation Ar string
.br
.Op Fl x Ar console_width | Fl Fl columns Ar console_width
.Op Fl c Ar string | Fl Fl center Ar string
.br
.Op Fl x Ar console_width | Fl Fl columns Ar console_width
.Op Fl s Ar left Ar separator Ar right | Fl Fl separator Ar left Ar separator Ar right
.br
.Op Fl b Ar string | Fl Fl size Ar string
.br
.Op Fl l Ar string | Fl Fl length Ar string
.br
.Op Fl w Ar string | Fl Fl width Ar string
.br
.Op Fl a Ar string | Fl Fl size-length-width Ar string
.br
.Op Fl t | Fl Fl terminal-info
.\" ###### Description ######################################################
.Sh DESCRIPTION
print-utf8 is a simple program to print UTF-8 strings in the console with
options for indentation, centering, separator as well as size/length/width
information.
If /dev/tty is not available to obtain the terminal width and height, the
default of 80x24 is assumed.
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following options are available:
.Bl -tag -width indent
.It Fl h | Fl Fl help
Prints command-line parameters.
.It Fl v | Fl version
Prints program version.
.It Fl n | Fl Fl newline
Add a newline to the output. Default: off.
.It Fl i Ar indentation Ar string | Fl Fl indent Ar indentation Ar string
Indent the string by the given number of characters (columns in the console). A negative number leads to left-justified text, a positive number leads to right-justified text.
.It Fl c Ar string | Fl Fl center Ar string
Center the string, using indentation based on the current console width.
.It Fl s Ar left Ar separator Ar right | Fl Fl separator Ar left Ar separator Ar right
Make a separator, consisting of a left part, a variable number of separator string occurrences, as well as a right part.
.It Fl x Ar console_width | Fl Fl columns Ar console_width
Set number of columns (console width) for "center" and "separator" functions
(see above). If below 1, the current console width (or 80 if unknown) is used.
Default: current console width.
.It Fl b Ar string | Fl Fl size Ar string
Print the size (bytes) of the string without ANSI control sequences.
.It Fl l Ar string | Fl Fl length Ar string
Print the length (in UTF-8 characters) of the string without ANSI control sequences.
.It Fl w Ar string | Fl Fl width Ar string
Print the width (columns in the console) of the string without ANSI control sequences.
.It Fl a Ar string | Fl Fl size-length-width Ar string
Printf the size, length and width of the string without ANSI control sequences.
.It Fl t | Fl Fl terminal-info
Print current width and height of the console.
Note that if /dev/tty is not available, the default of 80x24 is returned!
.El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It print-utf8 -h
.It print-utf8 --help
.It print-utf8 --version
.It print-utf8 --newline --center 'This line is centered in console width!'
.It print-utf8 --newline --columns 80 --center 'This line is centered in 80 columns!'
.It print-utf8 --newline --center '\ex1b[38;2;241;71;29mThis line is centered!\ee[0m'
.It print-utf8 -n -c '😀😀😀 This line is centered in console width! 😀😀😀'
.It print-utf8 -n -x 80 -c '😀😀😀 This line is centered in 80 columns! 😀😀😀'
.It print-utf8 --indent -32 'Left: ' && echo '1234'
.It print-utf8 --indent +32 'Right: ' && echo '1234'
.It print-utf8 --separator --newline '<*' '=' '*>'
.It print-utf8 --separator --columns 80 --newline '<*' '=' '*>'
.It print-utf8 -n -s '<💻😀' '=' '😀💻>'
.It print-utf8 --width 'Test'
.It print-utf8 --width 'Test äöü'
.It print-utf8 -s '😀 Test 😀'
.It print-utf8 -l '😀 Test 😀'
.It print-utf8 -w '😀 Test 😀'
.It print-utf8 -a '😀 Test 😀'
.It print-utf8 --terminal-info
.El
