.\" ==========================================================================
.\"         ____            _                     _____           _
.\"        / ___| _   _ ___| |_ ___ _ __ ___     |_   _|__   ___ | |___
.\"        \___ \| | | / __| __/ _ \ '_ ` _ \ _____| |/ _ \ / _ \| / __|
.\"         ___) | |_| \__ \ ||  __/ | | | | |_____| | (_) | (_) | \__ \
.\"        |____/ \__, |___/\__\___|_| |_| |_|     |_|\___/ \___/|_|___/
.\"               |___/
.\"                             --- System-Tools ---
.\"                  https://www.nntb.no/~dreibh/system-tools/
.\" ==========================================================================
.\"
.\" Reset-Machine-ID
.\" Copyright (C) 2024-2025 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: thomas.dreibholz@gmail.com
.\"
.\" ###### Setup ############################################################
.Dd May 11, 2025
.Dt Reset-Machine-ID 1
.Os Reset-Machine-ID
.\" ###### Name #############################################################
.Sh NAME
.Nm Reset-Machine-ID
.Nd resets the machine identity state
.\" ###### Synopsis #########################################################
.\" Manpage syntax help:
.\" https://forums.freebsd.org/threads/howto-create-a-manpage-from-scratch.13200/
.Sh SYNOPSIS
.Nm Reset-Machine-ID
.Op Fl H Ar hostname | Fl Fl hostname Ar hostname
.Op Fl Z Ar zabbix_server | Fl Fl zabbix Ar zabbix_server
.Op Fl A | Fl Fl install-zabbix-agent
.Op Fl M | Fl Fl skip-machine-id
.Op Fl S | Fl Fl skip-ssh-configuration
.Op Fl K | Fl Fl skip-ssh-key-replacement
.Op Fl Fl yes-to-all-i-am-really-sure
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm Reset-Machine-ID
resets the machine identity state, particularly for a cloned VM, to make it appear as a new machine.
It performs the following tasks:
.br
* Reset /etc/machine-id,
.br
* Reset /var/lib/dbus/machine-id (symlink to /etc/machine-id),
.br
* Change hostname, if a new one is provided (\-\-hostname parameter).
.br
* Provide hardened settings for SSH client and server.
.br
* Create new SSH key pair.
.br
The changes are made interactively on request, unless the option --yes-to-all-i-am-really-sure is used.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following options are available:
.Bl -tag -width indent
.It Fl H Ar hostname | Fl Fl hostname Ar hostname
Set the given hostname.
.It Fl Z Ar zabbix_server | Fl Fl zabbix Ar zabbix_server
Configure an already-installed Zabbix Agent for a given Zabbix server.
.It Fl A | Fl Fl install-zabbix-agent
Try to install Zabbix Agent, if necessary, when a Zabbix server is given but no Zabbix Agent is installed. This will add the current Zabbix PPA on Debian/Ubuntu/Fedora systems. Note that a Zabbix PPA may not be available for the used distribution! On FreeBSD, the Zabbix Agent is installed from the FreeBSD Ports Collection.
.It Fl M | Fl Fl skip-machine-id
Do not reset the machine ID.
.It Fl S | Fl Fl skip-ssh-configuration
Do not make SSH configuration changes.
.It Fl K | Fl Fl skip-ssh-key-replacement
Do not replace SSH keys.
.It Fl Fl yes-to-all-i-am-really-sure
Create new keys (delete old ones) as well as replace sshd_config and
ssh_config without interactively asking for confirmation.
.El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It sudo Reset-Machine-ID
.It sudo Reset-Machine-ID --yes-to-all-i-am-really-sure
.It sudo Reset-Machine-ID --hostname dbserver.domain.example
.It sudo Reset-Machine-ID -H server.domain.example -Z zabbix.domain.example -A
.It sudo Reset-Machine-ID -H server.domain.example --zabbix zabbix.domain.example --install-zabbix-agent
.It sudo Reset-Machine-ID --skip-ssh-configuration --skip-ssh-key-replacement
.El
