.\" Reset Machine ID
.\" Copyright (C) 2013-2024 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@simula.no
.\"
.\" ###### Setup ############################################################
.Dd August 29, 2024
.Dt Reset-Machine-ID 1
.Os Reset-Machine-ID
.\" ###### Name #############################################################
.Sh NAME
.Nm Reset-Machine-ID
.Nd resets the machine identity state
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm Reset-Machine-ID
.Op Fl \-hostname|\-H hostname
.Op Fl \-zabbix|\-Z zabbix_server
.Op Fl \-skip-machine-id|-M
.Op Fl \-skip-ssh-configuration|\-S
.Op Fl \-skip-ssh-key-replacement|\-K
.Op Fl \-yes\-to\-all\-i\-am\-really\-sure
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm Reset-Machine-ID
resets the machine identity state, particularly for a cloned VM, to make it appear as a new machine.
It performs the following tasks:
.br
* Reset /etc/machine-id,
.br
* Reset /var/lib/dbus/machine-id (symlink to /etc/machine-id),
.br
* Change hostname, if a new one is provided (\-\-hostname parameter).
.br
* Provide hardened settings for SSH client and server.
.br
* Create new SSH key pair.
.br
The changes are made interactively on request, unless the \-yes\-to\-all\-i\-am\-really\-sure is used.
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following options are available:
.Bl -tag -width indent
.It \-\-yes\-to\-all\-i\-am\-really\-sure
Create new keys (delete old ones) as well as replace sshd_config and
ssh_config without interactively asking for confirmation.
.It \-\-hostname|\-H hostname
Set the given hostname.
.It \-\-zabbix|\-Z zabbix_server
Configure an already-installed Zabbix agent for a given Zabbix server.
.It \-\-skip-machine-id|-M
Do not reset the machine ID.
.It \-\-skip-ssh-configuration
Do not make SSH configuration changes.
.It \-\-skip-ssh-key-replacement
Do not replace SSH keys.
.El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It sudo Reset-Machine-ID
.It sudo Reset-Machine-ID \-\-yes\-to\-all\-i\-am\-really\-sure
.It sudo Reset-Machine-ID \-\-hostname dbserver.domain.example
.It sudo Reset-Machine-ID \-H server.domain.example \-Z zabbix.domain.example
.It sudo Reset-Machine-ID \-\-skip\-ssh\-configuration \-\-skip\-ssh\-key\-replacement
.El
