.\" System-Maintenance
.\" Copyright (C) 2013-2023 by Thomas Dreibholz
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"
.\" Contact: dreibh@simula.no
.\"
.\" ###### Setup ############################################################
.Dd October 6, 2020
.Dt System-Maintenance 1
.Os System-Maintenance
.\" ###### Name #############################################################
.Sh NAME
.Nm System-Maintenance
.Nd System-Maintenance
.\" ###### Synopsis #########################################################
.Sh SYNOPSIS
.Nm System-Maintenance
.Op Fl interactive-kernel-removal|-k
.Op Fl dont-touch-grub|-g
.Op Fl dont-keep-interface-mappings|-m
.\" ###### Description ######################################################
.Sh DESCRIPTION
.Nm System-Maintenance
runs some system maintenance tasks to keep the system clean and up to date.
These tasks are:
.Bl -tag -width indent
.It Ensuring that all packages are configured (dpkg --configure -a),
.It Updating the package repositories,
.It Removing obsolete kernels,
.It Installing all available package updates,
.It Auto-removing unused packages,
.It Ensuring that Grub (the bootloader) is installed and up-to-date,
.It Delete network interface mapping (only on request by option, see below),
.It Updating package and file search caches.
.El
.Pp
.\" ###### Arguments ########################################################
.Sh ARGUMENTS
The following options are available:
.Bl -tag -width indent
.It Fl interactive-kernel-removal|-k
Remove obsolete kernels interactively.
.It Fl dont-touch-grub|-g
Do not update Grub installation.
.It Fl dont-keep-interface-mappings|-M
Delete network interface mapping rules
(/etc/udev/rules.d/70-persistent-net.rules), if eth0 does not exist. This is
useful for cloned virtual machines, where the new machine gets net MAC
addresses. By deleting the mappings, the interfaces should be renamed
beginning from eth0 during the next boot.
.El
.\" ###### Examples #########################################################
.Sh EXAMPLES
.Bl -tag -width indent
.It System-Maintenance
.It System-Maintenance -dont-keep-interface-mappings
.El
