#!/bin/bash

./t2 -n -s '<*' '=' '*>'
for indent in -20 +20 ; do
   echo "Indented ${indent}:"
   ./t2 -i ${indent} "Test: "
   echo "*"
   ./t2 -i ${indent} "Test äöüß ÆØÅ: "
   echo "*"
   ./t2 -i ${indent} "托马斯博士: "
   echo "*"
   ./t2 -i ${indent} "😀💻: "
   echo "*"
done

./t2 -n -s '<😀' '=' '😀>'
echo "Centered:"
./t2 -n -c "Test"
./t2 -n -c "äöüß"
./t2 -n -c "托马斯博士"

./t2 -n -s '<💻😀' '=' '😀💻>'
