#!/usr/bin/env bash

set -e

make text-block
for mode in extract remove ; do
   for o1 in include-tags exclude-tags ; do
      for o2 in tags-only full-tag-lines ; do
         for test in test1 test2 ; do
            if [ "$mode" == "extract" ] && [ "$test" == "test2" ] ; then
               continue
            fi
            echo >&2 -e "\n\n###### $test --$mode --$o1 --$o2 ######"
            if [ "$test" == "test1" ] ; then
               valgrind ./text-block -i test.txt -o x.txt -b '<BEGIN-BLOCK>' -e '<END-BLOCK>' --$mode --$o1 --$o2
            elif [ "$test" == "test2" ] ; then
               valgrind ./text-block -i test.txt -o x.txt -b '<MARKER>' --$mode --$o1 --$o2
            else
               false
            fi
            cat x.txt
         done
      done
   done
done
