#!/usr/bin/env bash
# ==========================================================================
#         ____            _                     _____           _
#        / ___| _   _ ___| |_ ___ _ __ ___     |_   _|__   ___ | |___
#        \___ \| | | / __| __/ _ \ '_ ` _ \ _____| |/ _ \ / _ \| / __|
#         ___) | |_| \__ \ ||  __/ | | | | |_____| | (_) | (_) | \__ \
#        |____/ \__, |___/\__\___|_| |_| |_|     |_|\___/ \___/|_|___/
#               |___/
#                             --- System-Tools ---
#                  https://www.nntb.no/~dreibh/system-tools/
# ==========================================================================
#
# A simple console clock, with Print-UTF8 and Figlet
# Copyright (C) 2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

# Bash options:
set -eu

while true ; do
   (
      # Clear screen:
      echo -en "\x1b[H\x1b[2J"

      # Print the clock:
      cols=$((COLUMNS - 8))
      print-utf8 -n -s "\e[1;34m╔" "═" "╗\e[0m"
      date +"%Y-%m-%d %H:%M:%S" | ( echo "" ; figlet -w ${cols} -f mono12 ) | \
         print-utf8 -n -C "\e[1;34m║\e[1;31m" "\e[1;34m║\e[0m"
      print-utf8 -n -s "\e[1;34m╚" "═" "╝\e[0m"
   ) | (
      if ! mbuffer -q -s 16k 2>/dev/null ; then
         if ! buffer -s 16k 2>/dev/null ; then
            cat
         fi
      fi
   )
   sleep 1
done
