#!/usr/bin/env bash
# ==========================================================================
#         ____            _                     _____           _
#        / ___| _   _ ___| |_ ___ _ __ ___     |_   _|__   ___ | |___
#        \___ \| | | / __| __/ _ \ '_ ` _ \ _____| |/ _ \ / _ \| / __|
#         ___) | |_| \__ \ ||  __/ | | | | |_____| | (_) | (_) | \__ \
#        |____/ \__, |___/\__\___|_| |_| |_|     |_|\___/ \___/|_|___/
#               |___/
#                             --- System-Tools ---
#                  https://www.nntb.no/~dreibh/system-tools/
# ==========================================================================
#
# Compress PDF
# Copyright (C) 2015-2026 by Thomas Dreibholz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Contact: thomas.dreibholz@gmail.com

if [ $# -ne 2 ] ; then
   echo >&2 "Usage: $0 input_pdf output_pdf"
   exit 1
fi

# -dPDFSETTINGS=configuration
#     Presets the "distiller parameters" to one of four predefined settings:
#
#         /screen selects low-resolution output similar to the Acrobat Distiller "Screen Optimized" setting.
#         /ebook selects medium-resolution output similar to the Acrobat Distiller "eBook" setting.
#         /printer selects output similar to the Acrobat Distiller "Print Optimized" setting.
#         /prepress selects output similar to Acrobat Distiller "Prepress Optimized" setting.
#         /default selects output intended to be useful across a wide variety of uses, possibly at the expense of a larger output file.

gs -sDEVICE=pdfwrite -dCompatibilityLevel=2.0 -dPDFSETTINGS=/prepress -dNOPAUSE -dQUIET -dBATCH "-sOutputFile=$2" "$1"
ls -al "$1" "$2"
