#!/usr/bin/env bash

set -eu

# ====== Print GURU Meditation ==============================================
NUMBER="$(printf "%08x.%08x" 0x00000004 "$((RANDOM * RANDOM))")"

print-utf8 -n -s "\e[1;31;40;5m█" "▀" "█\e[0m"
echo -e "Software Failure.   Press left mouse button to continue.\nGuru Meditation #${NUMBER}" | \
print-utf8 -n -C "\e[1;31;40;5m█\e[25m" "\e[5m█\e[0m"
print-utf8 -n -s "\e[1;31;40;5m█" "▄" "█\e[0m"
